var initialGraph = {nodes: [{nodeName: "Michael Jackson", group: 1}, 
{nodeName: "Chaka Khan", group: 1}, 
{nodeName: "Mary J. Blige", group: 1}, 
{nodeName: "Kanye West", group: 1}, 
{nodeName: "Britney Spears", group: 1}, 
{nodeName: "Cher", group: 1}, 
{nodeName: "Ella Fitzgerald", group: 1}, 
{nodeName: "U2", group: 1}, 
{nodeName: "Ray Charles", group: 1}, 
{nodeName: "Miles Davis", group: 1}, 
{nodeName: "Rod Stewart", group: 1}, 
{nodeName: "Emmylou Harris", group: 1}, 
{nodeName: "Elton John", group: 1}, 
{nodeName: "Willie Nelson", group: 1}, 
{nodeName: "John Lennon", group: 1}, 
{nodeName: "Eric Clapton", group: 1}, 
{nodeName: "Pink Floyd", group: 1}, 
{nodeName: "Elvis Costello", group: 1}, 
{nodeName: "Paul McCartney", group: 1}, 
{nodeName: "Madonna (entertainer)", group: 1}, 
{nodeName: "The Rolling Stones", group: 1}, 
{nodeName: "Jimi Hendrix", group: 1}, 
{nodeName: "Jay-Z", group: 1}, 
{nodeName: "Tina Turner", group: 1}, 
{nodeName: "Bonnie Raitt", group: 1}, 
{nodeName: "Janet Jackson", group: 1}, 
{nodeName: "Johnny Cash", group: 1}, 
{nodeName: "Quincy Jones", group: 1}, 
{nodeName: "Neil Young", group: 1}, 
{nodeName: "Diana Ross", group: 1}, 
{nodeName: "Barack Obama", group: 1}, 
{nodeName: "Frank Sinatra", group: 1}, 
{nodeName: "Joni Mitchell", group: 1}, 
{nodeName: "Christina Aguilera", group: 1}, 
{nodeName: "Barbra Streisand", group: 1}, 
{nodeName: "Sting (musician)", group: 1}, 
{nodeName: "Elvis Presley", group: 1}, 
{nodeName: "Stevie Wonder", group: 1}, 
{nodeName: "Prince (musician)", group: 1}, 
{nodeName: "Alicia Keys", group: 1}, 
{nodeName: "Mariah Carey", group: 1}, 
{nodeName: "Whitney Houston", group: 1}, 
{nodeName: "Bob Dylan", group: 1}, 
{nodeName: "Bruce Springsteen", group: 1}, 
{nodeName: "Celine Dion", group: 1}, 
{nodeName: "The Beatles", group: 1}, 
{nodeName: "Aretha Franklin", group: 1}, 
{nodeName: "Marvin Gaye", group: 1}, 
{nodeName: "Dolly Parton", group: 1}, 
{nodeName: "Bing Crosby", group: 1}, 
{nodeName: "Linda Ronstadt", group: 1}, 
{nodeName: "David Bowie", group: 1}], links:[{source: 50, target: 0, value: 1}, 
{source: 48, target: 0, value: 1}, 
{source: 25, target: 0, value: 1}, 
{source: 40, target: 0, value: 1}, 
{source: 19, target: 0, value: 1}, 
{source: 29, target: 0, value: 1}, 
{source: 4, target: 0, value: 1}, 
{source: 37, target: 0, value: 1}, 
{source: 5, target: 0, value: 1}, 
{source: 38, target: 0, value: 1}, 
{source: 41, target: 0, value: 1}, 
{source: 27, target: 0, value: 1}, 
{source: 22, target: 0, value: 1}, 
{source: 28, target: 0, value: 1}, 
{source: 44, target: 0, value: 1}, 
{source: 18, target: 0, value: 1}, 
{source: 49, target: 0, value: 1}, 
{source: 47, target: 0, value: 1}, 
{source: 45, target: 0, value: 1}, 
{source: 16, target: 0, value: 1}, 
{source: 9, target: 0, value: 1}, 
{source: 6, target: 1, value: 1}, 
{source: 19, target: 1, value: 1}, 
{source: 29, target: 1, value: 1}, 
{source: 37, target: 1, value: 1}, 
{source: 8, target: 1, value: 1}, 
{source: 5, target: 1, value: 1}, 
{source: 38, target: 1, value: 1}, 
{source: 41, target: 1, value: 1}, 
{source: 27, target: 1, value: 1}, 
{source: 32, target: 1, value: 1}, 
{source: 15, target: 1, value: 1}, 
{source: 2, target: 1, value: 1}, 
{source: 46, target: 1, value: 1}, 
{source: 25, target: 2, value: 1}, 
{source: 1, target: 2, value: 1}, 
{source: 40, target: 2, value: 1}, 
{source: 5, target: 2, value: 1}, 
{source: 41, target: 2, value: 1}, 
{source: 22, target: 2, value: 1}, 
{source: 44, target: 2, value: 1}, 
{source: 35, target: 2, value: 1}, 
{source: 46, target: 2, value: 1}, 
{source: 47, target: 2, value: 1}, 
{source: 7, target: 2, value: 1}, 
{source: 40, target: 3, value: 1}, 
{source: 37, target: 3, value: 1}, 
{source: 22, target: 3, value: 1}, 
{source: 32, target: 3, value: 1}, 
{source: 35, target: 3, value: 1}, 
{source: 12, target: 3, value: 1}, 
{source: 47, target: 3, value: 1}, 
{source: 33, target: 4, value: 1}, 
{source: 25, target: 4, value: 1}, 
{source: 40, target: 4, value: 1}, 
{source: 19, target: 4, value: 1}, 
{source: 0, target: 4, value: 1}, 
{source: 5, target: 4, value: 1}, 
{source: 39, target: 4, value: 1}, 
{source: 41, target: 4, value: 1}, 
{source: 3, target: 4, value: 1}, 
{source: 50, target: 5, value: 1}, 
{source: 48, target: 5, value: 1}, 
{source: 33, target: 5, value: 1}, 
{source: 25, target: 5, value: 1}, 
{source: 4, target: 5, value: 1}, 
{source: 41, target: 5, value: 1}, 
{source: 23, target: 5, value: 1}, 
{source: 34, target: 5, value: 1}, 
{source: 44, target: 5, value: 1}, 
{source: 10, target: 5, value: 1}, 
{source: 50, target: 6, value: 1}, 
{source: 19, target: 6, value: 1}, 
{source: 31, target: 6, value: 1}, 
{source: 34, target: 6, value: 1}, 
{source: 27, target: 6, value: 1}, 
{source: 25, target: 7, value: 1}, 
{source: 11, target: 7, value: 1}, 
{source: 13, target: 7, value: 1}, 
{source: 39, target: 7, value: 1}, 
{source: 23, target: 7, value: 1}, 
{source: 43, target: 7, value: 1}, 
{source: 27, target: 7, value: 1}, 
{source: 22, target: 7, value: 1}, 
{source: 44, target: 7, value: 1}, 
{source: 18, target: 7, value: 1}, 
{source: 2, target: 7, value: 1}, 
{source: 3, target: 7, value: 1}, 
{source: 26, target: 7, value: 1}, 
{source: 16, target: 7, value: 1}, 
{source: 20, target: 7, value: 1}, 
{source: 50, target: 8, value: 1}, 
{source: 1, target: 8, value: 1}, 
{source: 36, target: 8, value: 1}, 
{source: 13, target: 8, value: 1}, 
{source: 5, target: 8, value: 1}, 
{source: 39, target: 8, value: 1}, 
{source: 23, target: 8, value: 1}, 
{source: 27, target: 8, value: 1}, 
{source: 17, target: 8, value: 1}, 
{source: 12, target: 8, value: 1}, 
{source: 46, target: 8, value: 1}, 
{source: 26, target: 8, value: 1}, 
{source: 50, target: 9, value: 1}, 
{source: 37, target: 9, value: 1}, 
{source: 38, target: 9, value: 1}, 
{source: 27, target: 9, value: 1}, 
{source: 32, target: 9, value: 1}, 
{source: 35, target: 9, value: 1}, 
{source: 21, target: 9, value: 1}, 
{source: 20, target: 9, value: 1}, 
{source: 25, target: 10, value: 1}, 
{source: 29, target: 10, value: 1}, 
{source: 37, target: 10, value: 1}, 
{source: 5, target: 10, value: 1}, 
{source: 35, target: 10, value: 1}, 
{source: 47, target: 10, value: 1}, 
{source: 50, target: 11, value: 1}, 
{source: 48, target: 11, value: 1}, 
{source: 13, target: 11, value: 1}, 
{source: 43, target: 11, value: 1}, 
{source: 28, target: 11, value: 1}, 
{source: 32, target: 11, value: 1}, 
{source: 50, target: 12, value: 1}, 
{source: 33, target: 12, value: 1}, 
{source: 25, target: 12, value: 1}, 
{source: 40, target: 12, value: 1}, 
{source: 37, target: 12, value: 1}, 
{source: 42, target: 12, value: 1}, 
{source: 8, target: 12, value: 1}, 
{source: 5, target: 12, value: 1}, 
{source: 31, target: 12, value: 1}, 
{source: 23, target: 12, value: 1}, 
{source: 14, target: 12, value: 1}, 
{source: 10, target: 12, value: 1}, 
{source: 15, target: 12, value: 1}, 
{source: 17, target: 12, value: 1}, 
{source: 46, target: 12, value: 1}, 
{source: 47, target: 12, value: 1}, 
{source: 48, target: 13, value: 1}, 
{source: 11, target: 13, value: 1}, 
{source: 42, target: 13, value: 1}, 
{source: 8, target: 13, value: 1}, 
{source: 32, target: 13, value: 1}, 
{source: 17, target: 13, value: 1}, 
{source: 26, target: 13, value: 1}, 
{source: 50, target: 14, value: 1}, 
{source: 48, target: 14, value: 1}, 
{source: 33, target: 14, value: 1}, 
{source: 19, target: 14, value: 1}, 
{source: 37, target: 14, value: 1}, 
{source: 42, target: 14, value: 1}, 
{source: 28, target: 14, value: 1}, 
{source: 44, target: 14, value: 1}, 
{source: 15, target: 14, value: 1}, 
{source: 18, target: 14, value: 1}, 
{source: 12, target: 14, value: 1}, 
{source: 51, target: 14, value: 1}, 
{source: 45, target: 14, value: 1}, 
{source: 16, target: 14, value: 1}, 
{source: 20, target: 14, value: 1}, 
{source: 25, target: 15, value: 1}, 
{source: 42, target: 15, value: 1}, 
{source: 5, target: 15, value: 1}, 
{source: 14, target: 15, value: 1}, 
{source: 35, target: 15, value: 1}, 
{source: 12, target: 15, value: 1}, 
{source: 21, target: 15, value: 1}, 
{source: 26, target: 15, value: 1}, 
{source: 45, target: 15, value: 1}, 
{source: 15, target: 16, value: 1}, 
{source: 50, target: 17, value: 1}, 
{source: 11, target: 17, value: 1}, 
{source: 43, target: 17, value: 1}, 
{source: 32, target: 17, value: 1}, 
{source: 18, target: 17, value: 1}, 
{source: 12, target: 17, value: 1}, 
{source: 7, target: 17, value: 1}, 
{source: 37, target: 18, value: 1}, 
{source: 0, target: 18, value: 1}, 
{source: 42, target: 18, value: 1}, 
{source: 36, target: 18, value: 1}, 
{source: 23, target: 18, value: 1}, 
{source: 22, target: 18, value: 1}, 
{source: 28, target: 18, value: 1}, 
{source: 14, target: 18, value: 1}, 
{source: 15, target: 18, value: 1}, 
{source: 17, target: 18, value: 1}, 
{source: 21, target: 18, value: 1}, 
{source: 45, target: 18, value: 1}, 
{source: 16, target: 18, value: 1}, 
{source: 33, target: 19, value: 1}, 
{source: 25, target: 19, value: 1}, 
{source: 40, target: 19, value: 1}, 
{source: 29, target: 19, value: 1}, 
{source: 4, target: 19, value: 1}, 
{source: 0, target: 19, value: 1}, 
{source: 36, target: 19, value: 1}, 
{source: 5, target: 19, value: 1}, 
{source: 38, target: 19, value: 1}, 
{source: 34, target: 19, value: 1}, 
{source: 32, target: 19, value: 1}, 
{source: 12, target: 19, value: 1}, 
{source: 46, target: 19, value: 1}, 
{source: 50, target: 20, value: 1}, 
{source: 33, target: 20, value: 1}, 
{source: 25, target: 20, value: 1}, 
{source: 37, target: 20, value: 1}, 
{source: 39, target: 20, value: 1}, 
{source: 38, target: 20, value: 1}, 
{source: 14, target: 20, value: 1}, 
{source: 10, target: 20, value: 1}, 
{source: 15, target: 20, value: 1}, 
{source: 47, target: 20, value: 1}, 
{source: 21, target: 20, value: 1}, 
{source: 3, target: 20, value: 1}, 
{source: 7, target: 20, value: 1}, 
{source: 45, target: 20, value: 1}, 
{source: 9, target: 20, value: 1}, 
{source: 11, target: 21, value: 1}, 
{source: 42, target: 21, value: 1}, 
{source: 39, target: 21, value: 1}, 
{source: 38, target: 21, value: 1}, 
{source: 10, target: 21, value: 1}, 
{source: 15, target: 21, value: 1}, 
{source: 35, target: 21, value: 1}, 
{source: 16, target: 21, value: 1}, 
{source: 9, target: 21, value: 1}, 
{source: 40, target: 22, value: 1}, 
{source: 4, target: 22, value: 1}, 
{source: 39, target: 22, value: 1}, 
{source: 2, target: 22, value: 1}, 
{source: 3, target: 22, value: 1}, 
{source: 50, target: 23, value: 1}, 
{source: 25, target: 23, value: 1}, 
{source: 5, target: 23, value: 1}, 
{source: 41, target: 23, value: 1}, 
{source: 32, target: 23, value: 1}, 
{source: 44, target: 23, value: 1}, 
{source: 10, target: 23, value: 1}, 
{source: 15, target: 23, value: 1}, 
{source: 35, target: 23, value: 1}, 
{source: 2, target: 23, value: 1}, 
{source: 51, target: 23, value: 1}, 
{source: 46, target: 23, value: 1}, 
{source: 7, target: 23, value: 1}, 
{source: 25, target: 24, value: 1}, 
{source: 11, target: 24, value: 1}, 
{source: 13, target: 24, value: 1}, 
{source: 8, target: 24, value: 1}, 
{source: 33, target: 25, value: 1}, 
{source: 40, target: 25, value: 1}, 
{source: 19, target: 25, value: 1}, 
{source: 4, target: 25, value: 1}, 
{source: 0, target: 25, value: 1}, 
{source: 41, target: 25, value: 1}, 
{source: 32, target: 25, value: 1}, 
{source: 47, target: 25, value: 1}, 
{source: 3, target: 25, value: 1}, 
{source: 48, target: 26, value: 1}, 
{source: 11, target: 26, value: 1}, 
{source: 42, target: 26, value: 1}, 
{source: 36, target: 26, value: 1}, 
{source: 13, target: 26, value: 1}, 
{source: 43, target: 26, value: 1}, 
{source: 28, target: 26, value: 1}, 
{source: 7, target: 26, value: 1}, 
{source: 1, target: 27, value: 1}, 
{source: 6, target: 27, value: 1}, 
{source: 29, target: 27, value: 1}, 
{source: 37, target: 27, value: 1}, 
{source: 0, target: 27, value: 1}, 
{source: 8, target: 27, value: 1}, 
{source: 39, target: 27, value: 1}, 
{source: 31, target: 27, value: 1}, 
{source: 41, target: 27, value: 1}, 
{source: 9, target: 27, value: 1}, 
{source: 50, target: 28, value: 1}, 
{source: 48, target: 28, value: 1}, 
{source: 11, target: 28, value: 1}, 
{source: 42, target: 28, value: 1}, 
{source: 13, target: 28, value: 1}, 
{source: 41, target: 28, value: 1}, 
{source: 15, target: 28, value: 1}, 
{source: 26, target: 28, value: 1}, 
{source: 9, target: 28, value: 1}, 
{source: 25, target: 29, value: 1}, 
{source: 40, target: 29, value: 1}, 
{source: 0, target: 29, value: 1}, 
{source: 5, target: 29, value: 1}, 
{source: 41, target: 29, value: 1}, 
{source: 10, target: 29, value: 1}, 
{source: 47, target: 29, value: 1}, 
{source: 40, target: 30, value: 1}, 
{source: 37, target: 30, value: 1}, 
{source: 5, target: 30, value: 1}, 
{source: 39, target: 30, value: 1}, 
{source: 43, target: 30, value: 1}, 
{source: 27, target: 30, value: 1}, 
{source: 22, target: 30, value: 1}, 
{source: 18, target: 30, value: 1}, 
{source: 35, target: 30, value: 1}, 
{source: 2, target: 30, value: 1}, 
{source: 46, target: 30, value: 1}, 
{source: 3, target: 30, value: 1}, 
{source: 50, target: 31, value: 1}, 
{source: 6, target: 31, value: 1}, 
{source: 37, target: 31, value: 1}, 
{source: 36, target: 31, value: 1}, 
{source: 39, target: 31, value: 1}, 
{source: 34, target: 31, value: 1}, 
{source: 27, target: 31, value: 1}, 
{source: 44, target: 31, value: 1}, 
{source: 49, target: 31, value: 1}, 
{source: 50, target: 32, value: 1}, 
{source: 25, target: 32, value: 1}, 
{source: 11, target: 32, value: 1}, 
{source: 42, target: 32, value: 1}, 
{source: 31, target: 32, value: 1}, 
{source: 38, target: 32, value: 1}, 
{source: 23, target: 32, value: 1}, 
{source: 28, target: 32, value: 1}, 
{source: 17, target: 32, value: 1}, 
{source: 25, target: 33, value: 1}, 
{source: 40, target: 33, value: 1}, 
{source: 19, target: 33, value: 1}, 
{source: 4, target: 33, value: 1}, 
{source: 5, target: 33, value: 1}, 
{source: 39, target: 33, value: 1}, 
{source: 41, target: 33, value: 1}, 
{source: 17, target: 33, value: 1}, 
{source: 20, target: 33, value: 1}, 
{source: 33, target: 34, value: 1}, 
{source: 25, target: 34, value: 1}, 
{source: 40, target: 34, value: 1}, 
{source: 19, target: 34, value: 1}, 
{source: 37, target: 34, value: 1}, 
{source: 36, target: 34, value: 1}, 
{source: 39, target: 34, value: 1}, 
{source: 41, target: 34, value: 1}, 
{source: 44, target: 34, value: 1}, 
{source: 19, target: 35, value: 1}, 
{source: 37, target: 35, value: 1}, 
{source: 43, target: 35, value: 1}, 
{source: 10, target: 35, value: 1}, 
{source: 17, target: 35, value: 1}, 
{source: 2, target: 35, value: 1}, 
{source: 9, target: 35, value: 1}, 
{source: 20, target: 35, value: 1}, 
{source: 48, target: 36, value: 1}, 
{source: 40, target: 36, value: 1}, 
{source: 6, target: 36, value: 1}, 
{source: 19, target: 36, value: 1}, 
{source: 11, target: 36, value: 1}, 
{source: 37, target: 36, value: 1}, 
{source: 0, target: 36, value: 1}, 
{source: 42, target: 36, value: 1}, 
{source: 8, target: 36, value: 1}, 
{source: 5, target: 36, value: 1}, 
{source: 31, target: 36, value: 1}, 
{source: 23, target: 36, value: 1}, 
{source: 43, target: 36, value: 1}, 
{source: 34, target: 36, value: 1}, 
{source: 28, target: 36, value: 1}, 
{source: 44, target: 36, value: 1}, 
{source: 14, target: 36, value: 1}, 
{source: 18, target: 36, value: 1}, 
{source: 17, target: 36, value: 1}, 
{source: 12, target: 36, value: 1}, 
{source: 49, target: 36, value: 1}, 
{source: 51, target: 36, value: 1}, 
{source: 21, target: 36, value: 1}, 
{source: 26, target: 36, value: 1}, 
{source: 7, target: 36, value: 1}, 
{source: 45, target: 36, value: 1}, 
{source: 1, target: 37, value: 1}, 
{source: 40, target: 37, value: 1}, 
{source: 6, target: 37, value: 1}, 
{source: 29, target: 37, value: 1}, 
{source: 0, target: 37, value: 1}, 
{source: 39, target: 37, value: 1}, 
{source: 38, target: 37, value: 1}, 
{source: 41, target: 37, value: 1}, 
{source: 34, target: 37, value: 1}, 
{source: 27, target: 37, value: 1}, 
{source: 14, target: 37, value: 1}, 
{source: 10, target: 37, value: 1}, 
{source: 18, target: 37, value: 1}, 
{source: 35, target: 37, value: 1}, 
{source: 12, target: 37, value: 1}, 
{source: 2, target: 37, value: 1}, 
{source: 46, target: 37, value: 1}, 
{source: 47, target: 37, value: 1}, 
{source: 25, target: 38, value: 1}, 
{source: 1, target: 38, value: 1}, 
{source: 19, target: 38, value: 1}, 
{source: 24, target: 38, value: 1}, 
{source: 37, target: 38, value: 1}, 
{source: 42, target: 38, value: 1}, 
{source: 39, target: 38, value: 1}, 
{source: 32, target: 38, value: 1}, 
{source: 47, target: 38, value: 1}, 
{source: 21, target: 38, value: 1}, 
{source: 9, target: 38, value: 1}, 
{source: 33, target: 39, value: 1}, 
{source: 25, target: 39, value: 1}, 
{source: 29, target: 39, value: 1}, 
{source: 38, target: 39, value: 1}, 
{source: 41, target: 39, value: 1}, 
{source: 51, target: 39, value: 1}, 
{source: 3, target: 39, value: 1}, 
{source: 33, target: 40, value: 1}, 
{source: 25, target: 40, value: 1}, 
{source: 0, target: 40, value: 1}, 
{source: 36, target: 40, value: 1}, 
{source: 5, target: 40, value: 1}, 
{source: 41, target: 40, value: 1}, 
{source: 22, target: 40, value: 1}, 
{source: 44, target: 40, value: 1}, 
{source: 35, target: 40, value: 1}, 
{source: 48, target: 41, value: 1}, 
{source: 33, target: 41, value: 1}, 
{source: 25, target: 41, value: 1}, 
{source: 40, target: 41, value: 1}, 
{source: 4, target: 41, value: 1}, 
{source: 37, target: 41, value: 1}, 
{source: 0, target: 41, value: 1}, 
{source: 5, target: 41, value: 1}, 
{source: 39, target: 41, value: 1}, 
{source: 34, target: 41, value: 1}, 
{source: 44, target: 41, value: 1}, 
{source: 35, target: 41, value: 1}, 
{source: 2, target: 41, value: 1}, 
{source: 46, target: 41, value: 1}, 
{source: 50, target: 42, value: 1}, 
{source: 11, target: 42, value: 1}, 
{source: 37, target: 42, value: 1}, 
{source: 36, target: 42, value: 1}, 
{source: 13, target: 42, value: 1}, 
{source: 5, target: 42, value: 1}, 
{source: 31, target: 42, value: 1}, 
{source: 38, target: 42, value: 1}, 
{source: 43, target: 42, value: 1}, 
{source: 28, target: 42, value: 1}, 
{source: 32, target: 42, value: 1}, 
{source: 14, target: 42, value: 1}, 
{source: 10, target: 42, value: 1}, 
{source: 15, target: 42, value: 1}, 
{source: 18, target: 42, value: 1}, 
{source: 35, target: 42, value: 1}, 
{source: 21, target: 42, value: 1}, 
{source: 26, target: 42, value: 1}, 
{source: 7, target: 42, value: 1}, 
{source: 45, target: 42, value: 1}, 
{source: 20, target: 42, value: 1}, 
{source: 50, target: 43, value: 1}, 
{source: 25, target: 43, value: 1}, 
{source: 24, target: 43, value: 1}, 
{source: 11, target: 43, value: 1}, 
{source: 37, target: 43, value: 1}, 
{source: 42, target: 43, value: 1}, 
{source: 28, target: 43, value: 1}, 
{source: 35, target: 43, value: 1}, 
{source: 17, target: 43, value: 1}, 
{source: 7, target: 43, value: 1}, 
{source: 33, target: 44, value: 1}, 
{source: 40, target: 44, value: 1}, 
{source: 5, target: 44, value: 1}, 
{source: 41, target: 44, value: 1}, 
{source: 34, target: 44, value: 1}, 
{source: 27, target: 44, value: 1}, 
{source: 12, target: 44, value: 1}, 
{source: 40, target: 45, value: 1}, 
{source: 19, target: 45, value: 1}, 
{source: 29, target: 45, value: 1}, 
{source: 11, target: 45, value: 1}, 
{source: 0, target: 45, value: 1}, 
{source: 42, target: 45, value: 1}, 
{source: 36, target: 45, value: 1}, 
{source: 31, target: 45, value: 1}, 
{source: 38, target: 45, value: 1}, 
{source: 41, target: 45, value: 1}, 
{source: 34, target: 45, value: 1}, 
{source: 44, target: 45, value: 1}, 
{source: 14, target: 45, value: 1}, 
{source: 10, target: 45, value: 1}, 
{source: 15, target: 45, value: 1}, 
{source: 18, target: 45, value: 1}, 
{source: 17, target: 45, value: 1}, 
{source: 12, target: 45, value: 1}, 
{source: 49, target: 45, value: 1}, 
{source: 21, target: 45, value: 1}, 
{source: 7, target: 45, value: 1}, 
{source: 16, target: 45, value: 1}, 
{source: 33, target: 46, value: 1}, 
{source: 40, target: 46, value: 1}, 
{source: 6, target: 46, value: 1}, 
{source: 37, target: 46, value: 1}, 
{source: 41, target: 46, value: 1}, 
{source: 34, target: 46, value: 1}, 
{source: 44, target: 46, value: 1}, 
{source: 2, target: 46, value: 1}, 
{source: 47, target: 46, value: 1}, 
{source: 25, target: 47, value: 1}, 
{source: 19, target: 47, value: 1}, 
{source: 29, target: 47, value: 1}, 
{source: 37, target: 47, value: 1}, 
{source: 8, target: 47, value: 1}, 
{source: 39, target: 47, value: 1}, 
{source: 34, target: 47, value: 1}, 
{source: 27, target: 47, value: 1}, 
{source: 2, target: 47, value: 1}, 
{source: 46, target: 47, value: 1}, 
{source: 50, target: 48, value: 1}, 
{source: 11, target: 48, value: 1}, 
{source: 13, target: 48, value: 1}, 
{source: 5, target: 48, value: 1}, 
{source: 41, target: 48, value: 1}, 
{source: 10, target: 48, value: 1}, 
{source: 6, target: 49, value: 1}, 
{source: 8, target: 49, value: 1}, 
{source: 31, target: 49, value: 1}, 
{source: 51, target: 49, value: 1}, 
{source: 48, target: 50, value: 1}, 
{source: 6, target: 50, value: 1}, 
{source: 11, target: 50, value: 1}, 
{source: 5, target: 50, value: 1}, 
{source: 34, target: 50, value: 1}, 
{source: 28, target: 50, value: 1}, 
{source: 32, target: 50, value: 1}, 
{source: 49, target: 50, value: 1}, 
{source: 42, target: 51, value: 1}, 
{source: 5, target: 51, value: 1}, 
{source: 31, target: 51, value: 1}, 
{source: 23, target: 51, value: 1}, 
{source: 28, target: 51, value: 1}, 
{source: 14, target: 51, value: 1}, 
{source: 15, target: 51, value: 1}, 
{source: 18, target: 51, value: 1}, 
{source: 12, target: 51, value: 1}, 
{source: 49, target: 51, value: 1}, 
{source: 16, target: 51, value: 1}] };var frameInformation = {1 : {add: [{ nodeName: "Nirvana (band)" }, 
{ nodeName: "Billy Joel" }, 
{ nodeName: "Leonard Cohen" }, 
{ nodeName: "Duke Ellington" }], del: [], links: [{ source: "Linda Ronstadt", target: "Michael Jackson", value: 1 }, 
{ source: "Dolly Parton", target: "Michael Jackson", value: 1 }, 
{ source: "Janet Jackson", target: "Michael Jackson", value: 1 }, 
{ source: "Mariah Carey", target: "Michael Jackson", value: 1 }, 
{ source: "Madonna (entertainer)", target: "Michael Jackson", value: 1 }, 
{ source: "Diana Ross", target: "Michael Jackson", value: 1 }, 
{ source: "Britney Spears", target: "Michael Jackson", value: 1 }, 
{ source: "Stevie Wonder", target: "Michael Jackson", value: 1 }, 
{ source: "Cher", target: "Michael Jackson", value: 1 }, 
{ source: "Whitney Houston", target: "Michael Jackson", value: 1 }, 
{ source: "Prince (musician)", target: "Michael Jackson", value: 1 }, 
{ source: "Quincy Jones", target: "Michael Jackson", value: 1 }, 
{ source: "Jay-Z", target: "Michael Jackson", value: 1 }, 
{ source: "Neil Young", target: "Michael Jackson", value: 1 }, 
{ source: "Celine Dion", target: "Michael Jackson", value: 1 }, 
{ source: "Paul McCartney", target: "Michael Jackson", value: 1 }, 
{ source: "Billy Joel", target: "Michael Jackson", value: 1 }, 
{ source: "Marvin Gaye", target: "Michael Jackson", value: 1 }, 
{ source: "The Beatles", target: "Michael Jackson", value: 1 }, 
{ source: "Pink Floyd", target: "Michael Jackson", value: 1 }, 
{ source: "Nirvana (band)", target: "Michael Jackson", value: 1 }, 
{ source: "Miles Davis", target: "Michael Jackson", value: 1 }, 
{ source: "Alicia Keys", target: "Nirvana (band)", value: 1 }, 
{ source: "Neil Young", target: "Nirvana (band)", value: 1 }, 
{ source: "Ella Fitzgerald", target: "Chaka Khan", value: 1 }, 
{ source: "Madonna (entertainer)", target: "Chaka Khan", value: 1 }, 
{ source: "Diana Ross", target: "Chaka Khan", value: 1 }, 
{ source: "Stevie Wonder", target: "Chaka Khan", value: 1 }, 
{ source: "Ray Charles", target: "Chaka Khan", value: 1 }, 
{ source: "Cher", target: "Chaka Khan", value: 1 }, 
{ source: "Whitney Houston", target: "Chaka Khan", value: 1 }, 
{ source: "Prince (musician)", target: "Chaka Khan", value: 1 }, 
{ source: "Quincy Jones", target: "Chaka Khan", value: 1 }, 
{ source: "Joni Mitchell", target: "Chaka Khan", value: 1 }, 
{ source: "Eric Clapton", target: "Chaka Khan", value: 1 }, 
{ source: "Mary J. Blige", target: "Chaka Khan", value: 1 }, 
{ source: "Aretha Franklin", target: "Chaka Khan", value: 1 }, 
{ source: "Janet Jackson", target: "Mary J. Blige", value: 1 }, 
{ source: "Chaka Khan", target: "Mary J. Blige", value: 1 }, 
{ source: "Mariah Carey", target: "Mary J. Blige", value: 1 }, 
{ source: "Stevie Wonder", target: "Mary J. Blige", value: 1 }, 
{ source: "Cher", target: "Mary J. Blige", value: 1 }, 
{ source: "Whitney Houston", target: "Mary J. Blige", value: 1 }, 
{ source: "Jay-Z", target: "Mary J. Blige", value: 1 }, 
{ source: "Celine Dion", target: "Mary J. Blige", value: 1 }, 
{ source: "Sting (musician)", target: "Mary J. Blige", value: 1 }, 
{ source: "Aretha Franklin", target: "Mary J. Blige", value: 1 }, 
{ source: "Marvin Gaye", target: "Mary J. Blige", value: 1 }, 
{ source: "U2", target: "Mary J. Blige", value: 1 }, 
{ source: "Mariah Carey", target: "Kanye West", value: 1 }, 
{ source: "Jay-Z", target: "Kanye West", value: 1 }, 
{ source: "Joni Mitchell", target: "Kanye West", value: 1 }, 
{ source: "Sting (musician)", target: "Kanye West", value: 1 }, 
{ source: "Elton John", target: "Kanye West", value: 1 }, 
{ source: "Christina Aguilera", target: "Britney Spears", value: 1 }, 
{ source: "Janet Jackson", target: "Britney Spears", value: 1 }, 
{ source: "Mariah Carey", target: "Britney Spears", value: 1 }, 
{ source: "Madonna (entertainer)", target: "Britney Spears", value: 1 }, 
{ source: "Michael Jackson", target: "Britney Spears", value: 1 }, 
{ source: "Cher", target: "Britney Spears", value: 1 }, 
{ source: "Alicia Keys", target: "Britney Spears", value: 1 }, 
{ source: "Whitney Houston", target: "Britney Spears", value: 1 }, 
{ source: "Kanye West", target: "Britney Spears", value: 1 }, 
{ source: "Linda Ronstadt", target: "Cher", value: 1 }, 
{ source: "Dolly Parton", target: "Cher", value: 1 }, 
{ source: "Christina Aguilera", target: "Cher", value: 1 }, 
{ source: "Janet Jackson", target: "Cher", value: 1 }, 
{ source: "Britney Spears", target: "Cher", value: 1 }, 
{ source: "Whitney Houston", target: "Cher", value: 1 }, 
{ source: "Tina Turner", target: "Cher", value: 1 }, 
{ source: "Barbra Streisand", target: "Cher", value: 1 }, 
{ source: "Celine Dion", target: "Cher", value: 1 }, 
{ source: "Rod Stewart", target: "Cher", value: 1 }, 
{ source: "Linda Ronstadt", target: "Ella Fitzgerald", value: 1 }, 
{ source: "Madonna (entertainer)", target: "Ella Fitzgerald", value: 1 }, 
{ source: "Frank Sinatra", target: "Ella Fitzgerald", value: 1 }, 
{ source: "Barbra Streisand", target: "Ella Fitzgerald", value: 1 }, 
{ source: "Quincy Jones", target: "Ella Fitzgerald", value: 1 }, 
{ source: "Duke Ellington", target: "Ella Fitzgerald", value: 1 }, 
{ source: "Janet Jackson", target: "U2", value: 1 }, 
{ source: "Emmylou Harris", target: "U2", value: 1 }, 
{ source: "Willie Nelson", target: "U2", value: 1 }, 
{ source: "Alicia Keys", target: "U2", value: 1 }, 
{ source: "Tina Turner", target: "U2", value: 1 }, 
{ source: "Bruce Springsteen", target: "U2", value: 1 }, 
{ source: "Quincy Jones", target: "U2", value: 1 }, 
{ source: "Jay-Z", target: "U2", value: 1 }, 
{ source: "Leonard Cohen", target: "U2", value: 1 }, 
{ source: "Celine Dion", target: "U2", value: 1 }, 
{ source: "Paul McCartney", target: "U2", value: 1 }, 
{ source: "Mary J. Blige", target: "U2", value: 1 }, 
{ source: "Kanye West", target: "U2", value: 1 }, 
{ source: "Johnny Cash", target: "U2", value: 1 }, 
{ source: "Pink Floyd", target: "U2", value: 1 }, 
{ source: "The Rolling Stones", target: "U2", value: 1 }, 
{ source: "Linda Ronstadt", target: "Ray Charles", value: 1 }, 
{ source: "Chaka Khan", target: "Ray Charles", value: 1 }, 
{ source: "Elvis Presley", target: "Ray Charles", value: 1 }, 
{ source: "Willie Nelson", target: "Ray Charles", value: 1 }, 
{ source: "Cher", target: "Ray Charles", value: 1 }, 
{ source: "Alicia Keys", target: "Ray Charles", value: 1 }, 
{ source: "Tina Turner", target: "Ray Charles", value: 1 }, 
{ source: "Quincy Jones", target: "Ray Charles", value: 1 }, 
{ source: "Elvis Costello", target: "Ray Charles", value: 1 }, 
{ source: "Billy Joel", target: "Ray Charles", value: 1 }, 
{ source: "Elton John", target: "Ray Charles", value: 1 }, 
{ source: "Aretha Franklin", target: "Ray Charles", value: 1 }, 
{ source: "Johnny Cash", target: "Ray Charles", value: 1 }, 
{ source: "Ray Charles", target: "Billy Joel", value: 1 }, 
{ source: "Barbra Streisand", target: "Billy Joel", value: 1 }, 
{ source: "Paul McCartney", target: "Billy Joel", value: 1 }, 
{ source: "Sting (musician)", target: "Billy Joel", value: 1 }, 
{ source: "Elton John", target: "Billy Joel", value: 1 }, 
{ source: "Linda Ronstadt", target: "Miles Davis", value: 1 }, 
{ source: "Prince (musician)", target: "Miles Davis", value: 1 }, 
{ source: "Quincy Jones", target: "Miles Davis", value: 1 }, 
{ source: "Joni Mitchell", target: "Miles Davis", value: 1 }, 
{ source: "Sting (musician)", target: "Miles Davis", value: 1 }, 
{ source: "Jimi Hendrix", target: "Miles Davis", value: 1 }, 
{ source: "Duke Ellington", target: "Miles Davis", value: 1 }, 
{ source: "The Rolling Stones", target: "Miles Davis", value: 1 }, 
{ source: "Janet Jackson", target: "Rod Stewart", value: 1 }, 
{ source: "Diana Ross", target: "Rod Stewart", value: 1 }, 
{ source: "Cher", target: "Rod Stewart", value: 1 }, 
{ source: "Sting (musician)", target: "Rod Stewart", value: 1 }, 
{ source: "Marvin Gaye", target: "Rod Stewart", value: 1 }, 
{ source: "Linda Ronstadt", target: "Emmylou Harris", value: 1 }, 
{ source: "Dolly Parton", target: "Emmylou Harris", value: 1 }, 
{ source: "Willie Nelson", target: "Emmylou Harris", value: 1 }, 
{ source: "Bruce Springsteen", target: "Emmylou Harris", value: 1 }, 
{ source: "Neil Young", target: "Emmylou Harris", value: 1 }, 
{ source: "Joni Mitchell", target: "Emmylou Harris", value: 1 }, 
{ source: "Linda Ronstadt", target: "Elton John", value: 1 }, 
{ source: "Christina Aguilera", target: "Elton John", value: 1 }, 
{ source: "Janet Jackson", target: "Elton John", value: 1 }, 
{ source: "Mariah Carey", target: "Elton John", value: 1 }, 
{ source: "Stevie Wonder", target: "Elton John", value: 1 }, 
{ source: "Bob Dylan", target: "Elton John", value: 1 }, 
{ source: "Ray Charles", target: "Elton John", value: 1 }, 
{ source: "Cher", target: "Elton John", value: 1 }, 
{ source: "Frank Sinatra", target: "Elton John", value: 1 }, 
{ source: "Tina Turner", target: "Elton John", value: 1 }, 
{ source: "John Lennon", target: "Elton John", value: 1 }, 
{ source: "Rod Stewart", target: "Elton John", value: 1 }, 
{ source: "Eric Clapton", target: "Elton John", value: 1 }, 
{ source: "Elvis Costello", target: "Elton John", value: 1 }, 
{ source: "Billy Joel", target: "Elton John", value: 1 }, 
{ source: "Aretha Franklin", target: "Elton John", value: 1 }, 
{ source: "Marvin Gaye", target: "Elton John", value: 1 }, 
{ source: "Dolly Parton", target: "Willie Nelson", value: 1 }, 
{ source: "Emmylou Harris", target: "Willie Nelson", value: 1 }, 
{ source: "Bob Dylan", target: "Willie Nelson", value: 1 }, 
{ source: "Ray Charles", target: "Willie Nelson", value: 1 }, 
{ source: "Joni Mitchell", target: "Willie Nelson", value: 1 }, 
{ source: "Elvis Costello", target: "Willie Nelson", value: 1 }, 
{ source: "Johnny Cash", target: "Willie Nelson", value: 1 }, 
{ source: "Linda Ronstadt", target: "John Lennon", value: 1 }, 
{ source: "Dolly Parton", target: "John Lennon", value: 1 }, 
{ source: "Christina Aguilera", target: "John Lennon", value: 1 }, 
{ source: "Madonna (entertainer)", target: "John Lennon", value: 1 }, 
{ source: "Stevie Wonder", target: "John Lennon", value: 1 }, 
{ source: "Bob Dylan", target: "John Lennon", value: 1 }, 
{ source: "Neil Young", target: "John Lennon", value: 1 }, 
{ source: "Celine Dion", target: "John Lennon", value: 1 }, 
{ source: "Eric Clapton", target: "John Lennon", value: 1 }, 
{ source: "Paul McCartney", target: "John Lennon", value: 1 }, 
{ source: "Elton John", target: "John Lennon", value: 1 }, 
{ source: "David Bowie", target: "John Lennon", value: 1 }, 
{ source: "The Beatles", target: "John Lennon", value: 1 }, 
{ source: "Pink Floyd", target: "John Lennon", value: 1 }, 
{ source: "The Rolling Stones", target: "John Lennon", value: 1 }, 
{ source: "Janet Jackson", target: "Eric Clapton", value: 1 }, 
{ source: "Bob Dylan", target: "Eric Clapton", value: 1 }, 
{ source: "Cher", target: "Eric Clapton", value: 1 }, 
{ source: "John Lennon", target: "Eric Clapton", value: 1 }, 
{ source: "Sting (musician)", target: "Eric Clapton", value: 1 }, 
{ source: "Elton John", target: "Eric Clapton", value: 1 }, 
{ source: "Jimi Hendrix", target: "Eric Clapton", value: 1 }, 
{ source: "Johnny Cash", target: "Eric Clapton", value: 1 }, 
{ source: "The Beatles", target: "Eric Clapton", value: 1 }, 
{ source: "Eric Clapton", target: "Pink Floyd", value: 1 }, 
{ source: "Linda Ronstadt", target: "Elvis Costello", value: 1 }, 
{ source: "Emmylou Harris", target: "Elvis Costello", value: 1 }, 
{ source: "Bruce Springsteen", target: "Elvis Costello", value: 1 }, 
{ source: "Joni Mitchell", target: "Elvis Costello", value: 1 }, 
{ source: "Paul McCartney", target: "Elvis Costello", value: 1 }, 
{ source: "Elton John", target: "Elvis Costello", value: 1 }, 
{ source: "U2", target: "Elvis Costello", value: 1 }, 
{ source: "Stevie Wonder", target: "Paul McCartney", value: 1 }, 
{ source: "Michael Jackson", target: "Paul McCartney", value: 1 }, 
{ source: "Bob Dylan", target: "Paul McCartney", value: 1 }, 
{ source: "Elvis Presley", target: "Paul McCartney", value: 1 }, 
{ source: "Tina Turner", target: "Paul McCartney", value: 1 }, 
{ source: "Jay-Z", target: "Paul McCartney", value: 1 }, 
{ source: "Neil Young", target: "Paul McCartney", value: 1 }, 
{ source: "John Lennon", target: "Paul McCartney", value: 1 }, 
{ source: "Eric Clapton", target: "Paul McCartney", value: 1 }, 
{ source: "Elvis Costello", target: "Paul McCartney", value: 1 }, 
{ source: "Billy Joel", target: "Paul McCartney", value: 1 }, 
{ source: "Jimi Hendrix", target: "Paul McCartney", value: 1 }, 
{ source: "The Beatles", target: "Paul McCartney", value: 1 }, 
{ source: "Pink Floyd", target: "Paul McCartney", value: 1 }, 
{ source: "Christina Aguilera", target: "Madonna (entertainer)", value: 1 }, 
{ source: "Janet Jackson", target: "Madonna (entertainer)", value: 1 }, 
{ source: "Mariah Carey", target: "Madonna (entertainer)", value: 1 }, 
{ source: "Diana Ross", target: "Madonna (entertainer)", value: 1 }, 
{ source: "Britney Spears", target: "Madonna (entertainer)", value: 1 }, 
{ source: "Michael Jackson", target: "Madonna (entertainer)", value: 1 }, 
{ source: "Elvis Presley", target: "Madonna (entertainer)", value: 1 }, 
{ source: "Cher", target: "Madonna (entertainer)", value: 1 }, 
{ source: "Prince (musician)", target: "Madonna (entertainer)", value: 1 }, 
{ source: "Barbra Streisand", target: "Madonna (entertainer)", value: 1 }, 
{ source: "Joni Mitchell", target: "Madonna (entertainer)", value: 1 }, 
{ source: "Elton John", target: "Madonna (entertainer)", value: 1 }, 
{ source: "Aretha Franklin", target: "Madonna (entertainer)", value: 1 }, 
{ source: "Linda Ronstadt", target: "The Rolling Stones", value: 1 }, 
{ source: "Christina Aguilera", target: "The Rolling Stones", value: 1 }, 
{ source: "Janet Jackson", target: "The Rolling Stones", value: 1 }, 
{ source: "Stevie Wonder", target: "The Rolling Stones", value: 1 }, 
{ source: "Alicia Keys", target: "The Rolling Stones", value: 1 }, 
{ source: "Prince (musician)", target: "The Rolling Stones", value: 1 }, 
{ source: "John Lennon", target: "The Rolling Stones", value: 1 }, 
{ source: "Rod Stewart", target: "The Rolling Stones", value: 1 }, 
{ source: "Eric Clapton", target: "The Rolling Stones", value: 1 }, 
{ source: "Marvin Gaye", target: "The Rolling Stones", value: 1 }, 
{ source: "Jimi Hendrix", target: "The Rolling Stones", value: 1 }, 
{ source: "Kanye West", target: "The Rolling Stones", value: 1 }, 
{ source: "U2", target: "The Rolling Stones", value: 1 }, 
{ source: "The Beatles", target: "The Rolling Stones", value: 1 }, 
{ source: "Miles Davis", target: "The Rolling Stones", value: 1 }, 
{ source: "Emmylou Harris", target: "Jimi Hendrix", value: 1 }, 
{ source: "Bob Dylan", target: "Jimi Hendrix", value: 1 }, 
{ source: "Alicia Keys", target: "Jimi Hendrix", value: 1 }, 
{ source: "Prince (musician)", target: "Jimi Hendrix", value: 1 }, 
{ source: "Rod Stewart", target: "Jimi Hendrix", value: 1 }, 
{ source: "Eric Clapton", target: "Jimi Hendrix", value: 1 }, 
{ source: "Sting (musician)", target: "Jimi Hendrix", value: 1 }, 
{ source: "Pink Floyd", target: "Jimi Hendrix", value: 1 }, 
{ source: "Miles Davis", target: "Jimi Hendrix", value: 1 }, 
{ source: "Joni Mitchell", target: "Leonard Cohen", value: 1 }, 
{ source: "U2", target: "Leonard Cohen", value: 1 }, 
{ source: "Mariah Carey", target: "Jay-Z", value: 1 }, 
{ source: "Britney Spears", target: "Jay-Z", value: 1 }, 
{ source: "Alicia Keys", target: "Jay-Z", value: 1 }, 
{ source: "Mary J. Blige", target: "Jay-Z", value: 1 }, 
{ source: "Kanye West", target: "Jay-Z", value: 1 }, 
{ source: "Linda Ronstadt", target: "Tina Turner", value: 1 }, 
{ source: "Janet Jackson", target: "Tina Turner", value: 1 }, 
{ source: "Cher", target: "Tina Turner", value: 1 }, 
{ source: "Whitney Houston", target: "Tina Turner", value: 1 }, 
{ source: "Joni Mitchell", target: "Tina Turner", value: 1 }, 
{ source: "Celine Dion", target: "Tina Turner", value: 1 }, 
{ source: "Rod Stewart", target: "Tina Turner", value: 1 }, 
{ source: "Eric Clapton", target: "Tina Turner", value: 1 }, 
{ source: "Sting (musician)", target: "Tina Turner", value: 1 }, 
{ source: "Mary J. Blige", target: "Tina Turner", value: 1 }, 
{ source: "David Bowie", target: "Tina Turner", value: 1 }, 
{ source: "Aretha Franklin", target: "Tina Turner", value: 1 }, 
{ source: "U2", target: "Tina Turner", value: 1 }, 
{ source: "Janet Jackson", target: "Bonnie Raitt", value: 1 }, 
{ source: "Emmylou Harris", target: "Bonnie Raitt", value: 1 }, 
{ source: "Willie Nelson", target: "Bonnie Raitt", value: 1 }, 
{ source: "Ray Charles", target: "Bonnie Raitt", value: 1 }, 
{ source: "Christina Aguilera", target: "Janet Jackson", value: 1 }, 
{ source: "Mariah Carey", target: "Janet Jackson", value: 1 }, 
{ source: "Madonna (entertainer)", target: "Janet Jackson", value: 1 }, 
{ source: "Britney Spears", target: "Janet Jackson", value: 1 }, 
{ source: "Michael Jackson", target: "Janet Jackson", value: 1 }, 
{ source: "Whitney Houston", target: "Janet Jackson", value: 1 }, 
{ source: "Joni Mitchell", target: "Janet Jackson", value: 1 }, 
{ source: "Mary J. Blige", target: "Janet Jackson", value: 1 }, 
{ source: "Marvin Gaye", target: "Janet Jackson", value: 1 }, 
{ source: "Kanye West", target: "Janet Jackson", value: 1 }, 
{ source: "Dolly Parton", target: "Johnny Cash", value: 1 }, 
{ source: "Emmylou Harris", target: "Johnny Cash", value: 1 }, 
{ source: "Bob Dylan", target: "Johnny Cash", value: 1 }, 
{ source: "Elvis Presley", target: "Johnny Cash", value: 1 }, 
{ source: "Willie Nelson", target: "Johnny Cash", value: 1 }, 
{ source: "Bruce Springsteen", target: "Johnny Cash", value: 1 }, 
{ source: "Neil Young", target: "Johnny Cash", value: 1 }, 
{ source: "Leonard Cohen", target: "Johnny Cash", value: 1 }, 
{ source: "U2", target: "Johnny Cash", value: 1 }, 
{ source: "Chaka Khan", target: "Quincy Jones", value: 1 }, 
{ source: "Ella Fitzgerald", target: "Quincy Jones", value: 1 }, 
{ source: "Diana Ross", target: "Quincy Jones", value: 1 }, 
{ source: "Stevie Wonder", target: "Quincy Jones", value: 1 }, 
{ source: "Michael Jackson", target: "Quincy Jones", value: 1 }, 
{ source: "Ray Charles", target: "Quincy Jones", value: 1 }, 
{ source: "Alicia Keys", target: "Quincy Jones", value: 1 }, 
{ source: "Whitney Houston", target: "Quincy Jones", value: 1 }, 
{ source: "Frank Sinatra", target: "Quincy Jones", value: 1 }, 
{ source: "Miles Davis", target: "Quincy Jones", value: 1 }, 
{ source: "Linda Ronstadt", target: "Neil Young", value: 1 }, 
{ source: "Dolly Parton", target: "Neil Young", value: 1 }, 
{ source: "Emmylou Harris", target: "Neil Young", value: 1 }, 
{ source: "Bob Dylan", target: "Neil Young", value: 1 }, 
{ source: "Willie Nelson", target: "Neil Young", value: 1 }, 
{ source: "Whitney Houston", target: "Neil Young", value: 1 }, 
{ source: "Eric Clapton", target: "Neil Young", value: 1 }, 
{ source: "Johnny Cash", target: "Neil Young", value: 1 }, 
{ source: "Miles Davis", target: "Neil Young", value: 1 }, 
{ source: "Janet Jackson", target: "Diana Ross", value: 1 }, 
{ source: "Mariah Carey", target: "Diana Ross", value: 1 }, 
{ source: "Michael Jackson", target: "Diana Ross", value: 1 }, 
{ source: "Cher", target: "Diana Ross", value: 1 }, 
{ source: "Whitney Houston", target: "Diana Ross", value: 1 }, 
{ source: "Rod Stewart", target: "Diana Ross", value: 1 }, 
{ source: "Marvin Gaye", target: "Diana Ross", value: 1 }, 
{ source: "Mariah Carey", target: "Barack Obama", value: 1 }, 
{ source: "Cher", target: "Barack Obama", value: 1 }, 
{ source: "Alicia Keys", target: "Barack Obama", value: 1 }, 
{ source: "Bruce Springsteen", target: "Barack Obama", value: 1 }, 
{ source: "Quincy Jones", target: "Barack Obama", value: 1 }, 
{ source: "Jay-Z", target: "Barack Obama", value: 1 }, 
{ source: "Paul McCartney", target: "Barack Obama", value: 1 }, 
{ source: "Sting (musician)", target: "Barack Obama", value: 1 }, 
{ source: "Mary J. Blige", target: "Barack Obama", value: 1 }, 
{ source: "Aretha Franklin", target: "Barack Obama", value: 1 }, 
{ source: "Kanye West", target: "Barack Obama", value: 1 }, 
{ source: "Linda Ronstadt", target: "Frank Sinatra", value: 1 }, 
{ source: "Ella Fitzgerald", target: "Frank Sinatra", value: 1 }, 
{ source: "Elvis Presley", target: "Frank Sinatra", value: 1 }, 
{ source: "Alicia Keys", target: "Frank Sinatra", value: 1 }, 
{ source: "Barbra Streisand", target: "Frank Sinatra", value: 1 }, 
{ source: "Quincy Jones", target: "Frank Sinatra", value: 1 }, 
{ source: "Celine Dion", target: "Frank Sinatra", value: 1 }, 
{ source: "Billy Joel", target: "Frank Sinatra", value: 1 }, 
{ source: "Bing Crosby", target: "Frank Sinatra", value: 1 }, 
{ source: "Duke Ellington", target: "Frank Sinatra", value: 1 }, 
{ source: "Linda Ronstadt", target: "Joni Mitchell", value: 1 }, 
{ source: "Janet Jackson", target: "Joni Mitchell", value: 1 }, 
{ source: "Emmylou Harris", target: "Joni Mitchell", value: 1 }, 
{ source: "Bob Dylan", target: "Joni Mitchell", value: 1 }, 
{ source: "Prince (musician)", target: "Joni Mitchell", value: 1 }, 
{ source: "Frank Sinatra", target: "Joni Mitchell", value: 1 }, 
{ source: "Tina Turner", target: "Joni Mitchell", value: 1 }, 
{ source: "Neil Young", target: "Joni Mitchell", value: 1 }, 
{ source: "Leonard Cohen", target: "Joni Mitchell", value: 1 }, 
{ source: "Elvis Costello", target: "Joni Mitchell", value: 1 }, 
{ source: "Janet Jackson", target: "Christina Aguilera", value: 1 }, 
{ source: "Mariah Carey", target: "Christina Aguilera", value: 1 }, 
{ source: "Madonna (entertainer)", target: "Christina Aguilera", value: 1 }, 
{ source: "Britney Spears", target: "Christina Aguilera", value: 1 }, 
{ source: "Cher", target: "Christina Aguilera", value: 1 }, 
{ source: "Alicia Keys", target: "Christina Aguilera", value: 1 }, 
{ source: "Whitney Houston", target: "Christina Aguilera", value: 1 }, 
{ source: "Elvis Costello", target: "Christina Aguilera", value: 1 }, 
{ source: "The Rolling Stones", target: "Christina Aguilera", value: 1 }, 
{ source: "Christina Aguilera", target: "Barbra Streisand", value: 1 }, 
{ source: "Janet Jackson", target: "Barbra Streisand", value: 1 }, 
{ source: "Mariah Carey", target: "Barbra Streisand", value: 1 }, 
{ source: "Madonna (entertainer)", target: "Barbra Streisand", value: 1 }, 
{ source: "Stevie Wonder", target: "Barbra Streisand", value: 1 }, 
{ source: "Elvis Presley", target: "Barbra Streisand", value: 1 }, 
{ source: "Alicia Keys", target: "Barbra Streisand", value: 1 }, 
{ source: "Whitney Houston", target: "Barbra Streisand", value: 1 }, 
{ source: "Celine Dion", target: "Barbra Streisand", value: 1 }, 
{ source: "Billy Joel", target: "Barbra Streisand", value: 1 }, 
{ source: "Madonna (entertainer)", target: "Sting (musician)", value: 1 }, 
{ source: "Stevie Wonder", target: "Sting (musician)", value: 1 }, 
{ source: "Bruce Springsteen", target: "Sting (musician)", value: 1 }, 
{ source: "Rod Stewart", target: "Sting (musician)", value: 1 }, 
{ source: "Elvis Costello", target: "Sting (musician)", value: 1 }, 
{ source: "Mary J. Blige", target: "Sting (musician)", value: 1 }, 
{ source: "Miles Davis", target: "Sting (musician)", value: 1 }, 
{ source: "The Rolling Stones", target: "Sting (musician)", value: 1 }, 
{ source: "Linda Ronstadt", target: "Elvis Presley", value: 1 }, 
{ source: "Dolly Parton", target: "Elvis Presley", value: 1 }, 
{ source: "Mariah Carey", target: "Elvis Presley", value: 1 }, 
{ source: "Ella Fitzgerald", target: "Elvis Presley", value: 1 }, 
{ source: "Madonna (entertainer)", target: "Elvis Presley", value: 1 }, 
{ source: "Emmylou Harris", target: "Elvis Presley", value: 1 }, 
{ source: "Michael Jackson", target: "Elvis Presley", value: 1 }, 
{ source: "Bob Dylan", target: "Elvis Presley", value: 1 }, 
{ source: "Ray Charles", target: "Elvis Presley", value: 1 }, 
{ source: "Cher", target: "Elvis Presley", value: 1 }, 
{ source: "Frank Sinatra", target: "Elvis Presley", value: 1 }, 
{ source: "Tina Turner", target: "Elvis Presley", value: 1 }, 
{ source: "Bruce Springsteen", target: "Elvis Presley", value: 1 }, 
{ source: "Barbra Streisand", target: "Elvis Presley", value: 1 }, 
{ source: "Neil Young", target: "Elvis Presley", value: 1 }, 
{ source: "Celine Dion", target: "Elvis Presley", value: 1 }, 
{ source: "John Lennon", target: "Elvis Presley", value: 1 }, 
{ source: "Paul McCartney", target: "Elvis Presley", value: 1 }, 
{ source: "Elvis Costello", target: "Elvis Presley", value: 1 }, 
{ source: "Billy Joel", target: "Elvis Presley", value: 1 }, 
{ source: "Elton John", target: "Elvis Presley", value: 1 }, 
{ source: "David Bowie", target: "Elvis Presley", value: 1 }, 
{ source: "Jimi Hendrix", target: "Elvis Presley", value: 1 }, 
{ source: "Johnny Cash", target: "Elvis Presley", value: 1 }, 
{ source: "U2", target: "Elvis Presley", value: 1 }, 
{ source: "The Beatles", target: "Elvis Presley", value: 1 }, 
{ source: "Duke Ellington", target: "Elvis Presley", value: 1 }, 
{ source: "Chaka Khan", target: "Stevie Wonder", value: 1 }, 
{ source: "Mariah Carey", target: "Stevie Wonder", value: 1 }, 
{ source: "Ella Fitzgerald", target: "Stevie Wonder", value: 1 }, 
{ source: "Diana Ross", target: "Stevie Wonder", value: 1 }, 
{ source: "Michael Jackson", target: "Stevie Wonder", value: 1 }, 
{ source: "Alicia Keys", target: "Stevie Wonder", value: 1 }, 
{ source: "Whitney Houston", target: "Stevie Wonder", value: 1 }, 
{ source: "Prince (musician)", target: "Stevie Wonder", value: 1 }, 
{ source: "Barbra Streisand", target: "Stevie Wonder", value: 1 }, 
{ source: "Quincy Jones", target: "Stevie Wonder", value: 1 }, 
{ source: "John Lennon", target: "Stevie Wonder", value: 1 }, 
{ source: "Rod Stewart", target: "Stevie Wonder", value: 1 }, 
{ source: "Paul McCartney", target: "Stevie Wonder", value: 1 }, 
{ source: "Sting (musician)", target: "Stevie Wonder", value: 1 }, 
{ source: "Billy Joel", target: "Stevie Wonder", value: 1 }, 
{ source: "Elton John", target: "Stevie Wonder", value: 1 }, 
{ source: "Mary J. Blige", target: "Stevie Wonder", value: 1 }, 
{ source: "Aretha Franklin", target: "Stevie Wonder", value: 1 }, 
{ source: "Marvin Gaye", target: "Stevie Wonder", value: 1 }, 
{ source: "Duke Ellington", target: "Stevie Wonder", value: 1 }, 
{ source: "Janet Jackson", target: "Prince (musician)", value: 1 }, 
{ source: "Chaka Khan", target: "Prince (musician)", value: 1 }, 
{ source: "Madonna (entertainer)", target: "Prince (musician)", value: 1 }, 
{ source: "Bonnie Raitt", target: "Prince (musician)", value: 1 }, 
{ source: "Stevie Wonder", target: "Prince (musician)", value: 1 }, 
{ source: "Bob Dylan", target: "Prince (musician)", value: 1 }, 
{ source: "Alicia Keys", target: "Prince (musician)", value: 1 }, 
{ source: "Joni Mitchell", target: "Prince (musician)", value: 1 }, 
{ source: "Marvin Gaye", target: "Prince (musician)", value: 1 }, 
{ source: "Jimi Hendrix", target: "Prince (musician)", value: 1 }, 
{ source: "Miles Davis", target: "Prince (musician)", value: 1 }, 
{ source: "Christina Aguilera", target: "Alicia Keys", value: 1 }, 
{ source: "Janet Jackson", target: "Alicia Keys", value: 1 }, 
{ source: "Diana Ross", target: "Alicia Keys", value: 1 }, 
{ source: "Whitney Houston", target: "Alicia Keys", value: 1 }, 
{ source: "Prince (musician)", target: "Alicia Keys", value: 1 }, 
{ source: "David Bowie", target: "Alicia Keys", value: 1 }, 
{ source: "Kanye West", target: "Alicia Keys", value: 1 }, 
{ source: "Christina Aguilera", target: "Mariah Carey", value: 1 }, 
{ source: "Janet Jackson", target: "Mariah Carey", value: 1 }, 
{ source: "Britney Spears", target: "Mariah Carey", value: 1 }, 
{ source: "Michael Jackson", target: "Mariah Carey", value: 1 }, 
{ source: "Elvis Presley", target: "Mariah Carey", value: 1 }, 
{ source: "Cher", target: "Mariah Carey", value: 1 }, 
{ source: "Whitney Houston", target: "Mariah Carey", value: 1 }, 
{ source: "Jay-Z", target: "Mariah Carey", value: 1 }, 
{ source: "Celine Dion", target: "Mariah Carey", value: 1 }, 
{ source: "Sting (musician)", target: "Mariah Carey", value: 1 }, 
{ source: "Mary J. Blige", target: "Mariah Carey", value: 1 }, 
{ source: "Dolly Parton", target: "Whitney Houston", value: 1 }, 
{ source: "Christina Aguilera", target: "Whitney Houston", value: 1 }, 
{ source: "Janet Jackson", target: "Whitney Houston", value: 1 }, 
{ source: "Mariah Carey", target: "Whitney Houston", value: 1 }, 
{ source: "Diana Ross", target: "Whitney Houston", value: 1 }, 
{ source: "Britney Spears", target: "Whitney Houston", value: 1 }, 
{ source: "Michael Jackson", target: "Whitney Houston", value: 1 }, 
{ source: "Cher", target: "Whitney Houston", value: 1 }, 
{ source: "Alicia Keys", target: "Whitney Houston", value: 1 }, 
{ source: "Barbra Streisand", target: "Whitney Houston", value: 1 }, 
{ source: "Celine Dion", target: "Whitney Houston", value: 1 }, 
{ source: "Sting (musician)", target: "Whitney Houston", value: 1 }, 
{ source: "Mary J. Blige", target: "Whitney Houston", value: 1 }, 
{ source: "Aretha Franklin", target: "Whitney Houston", value: 1 }, 
{ source: "Linda Ronstadt", target: "Bob Dylan", value: 1 }, 
{ source: "Emmylou Harris", target: "Bob Dylan", value: 1 }, 
{ source: "Stevie Wonder", target: "Bob Dylan", value: 1 }, 
{ source: "Elvis Presley", target: "Bob Dylan", value: 1 }, 
{ source: "Willie Nelson", target: "Bob Dylan", value: 1 }, 
{ source: "Cher", target: "Bob Dylan", value: 1 }, 
{ source: "Prince (musician)", target: "Bob Dylan", value: 1 }, 
{ source: "Frank Sinatra", target: "Bob Dylan", value: 1 }, 
{ source: "Bruce Springsteen", target: "Bob Dylan", value: 1 }, 
{ source: "Neil Young", target: "Bob Dylan", value: 1 }, 
{ source: "Joni Mitchell", target: "Bob Dylan", value: 1 }, 
{ source: "Leonard Cohen", target: "Bob Dylan", value: 1 }, 
{ source: "John Lennon", target: "Bob Dylan", value: 1 }, 
{ source: "Rod Stewart", target: "Bob Dylan", value: 1 }, 
{ source: "Eric Clapton", target: "Bob Dylan", value: 1 }, 
{ source: "Paul McCartney", target: "Bob Dylan", value: 1 }, 
{ source: "Sting (musician)", target: "Bob Dylan", value: 1 }, 
{ source: "Billy Joel", target: "Bob Dylan", value: 1 }, 
{ source: "Jimi Hendrix", target: "Bob Dylan", value: 1 }, 
{ source: "Johnny Cash", target: "Bob Dylan", value: 1 }, 
{ source: "U2", target: "Bob Dylan", value: 1 }, 
{ source: "The Beatles", target: "Bob Dylan", value: 1 }, 
{ source: "The Rolling Stones", target: "Bob Dylan", value: 1 }, 
{ source: "Linda Ronstadt", target: "Bruce Springsteen", value: 1 }, 
{ source: "Janet Jackson", target: "Bruce Springsteen", value: 1 }, 
{ source: "Bonnie Raitt", target: "Bruce Springsteen", value: 1 }, 
{ source: "Emmylou Harris", target: "Bruce Springsteen", value: 1 }, 
{ source: "Stevie Wonder", target: "Bruce Springsteen", value: 1 }, 
{ source: "Bob Dylan", target: "Bruce Springsteen", value: 1 }, 
{ source: "Neil Young", target: "Bruce Springsteen", value: 1 }, 
{ source: "Sting (musician)", target: "Bruce Springsteen", value: 1 }, 
{ source: "Elvis Costello", target: "Bruce Springsteen", value: 1 }, 
{ source: "Billy Joel", target: "Bruce Springsteen", value: 1 }, 
{ source: "U2", target: "Bruce Springsteen", value: 1 }, 
{ source: "Christina Aguilera", target: "Celine Dion", value: 1 }, 
{ source: "Mariah Carey", target: "Celine Dion", value: 1 }, 
{ source: "Cher", target: "Celine Dion", value: 1 }, 
{ source: "Whitney Houston", target: "Celine Dion", value: 1 }, 
{ source: "Barbra Streisand", target: "Celine Dion", value: 1 }, 
{ source: "Quincy Jones", target: "Celine Dion", value: 1 }, 
{ source: "Elton John", target: "Celine Dion", value: 1 }, 
{ source: "Mariah Carey", target: "The Beatles", value: 1 }, 
{ source: "Madonna (entertainer)", target: "The Beatles", value: 1 }, 
{ source: "Emmylou Harris", target: "The Beatles", value: 1 }, 
{ source: "Michael Jackson", target: "The Beatles", value: 1 }, 
{ source: "Bob Dylan", target: "The Beatles", value: 1 }, 
{ source: "Elvis Presley", target: "The Beatles", value: 1 }, 
{ source: "Whitney Houston", target: "The Beatles", value: 1 }, 
{ source: "Prince (musician)", target: "The Beatles", value: 1 }, 
{ source: "Frank Sinatra", target: "The Beatles", value: 1 }, 
{ source: "Barbra Streisand", target: "The Beatles", value: 1 }, 
{ source: "Celine Dion", target: "The Beatles", value: 1 }, 
{ source: "John Lennon", target: "The Beatles", value: 1 }, 
{ source: "Rod Stewart", target: "The Beatles", value: 1 }, 
{ source: "Eric Clapton", target: "The Beatles", value: 1 }, 
{ source: "Paul McCartney", target: "The Beatles", value: 1 }, 
{ source: "Elvis Costello", target: "The Beatles", value: 1 }, 
{ source: "Billy Joel", target: "The Beatles", value: 1 }, 
{ source: "Elton John", target: "The Beatles", value: 1 }, 
{ source: "Jimi Hendrix", target: "The Beatles", value: 1 }, 
{ source: "U2", target: "The Beatles", value: 1 }, 
{ source: "Pink Floyd", target: "The Beatles", value: 1 }, 
{ source: "Christina Aguilera", target: "Aretha Franklin", value: 1 }, 
{ source: "Mariah Carey", target: "Aretha Franklin", value: 1 }, 
{ source: "Ella Fitzgerald", target: "Aretha Franklin", value: 1 }, 
{ source: "Stevie Wonder", target: "Aretha Franklin", value: 1 }, 
{ source: "Whitney Houston", target: "Aretha Franklin", value: 1 }, 
{ source: "Barbra Streisand", target: "Aretha Franklin", value: 1 }, 
{ source: "Celine Dion", target: "Aretha Franklin", value: 1 }, 
{ source: "Mary J. Blige", target: "Aretha Franklin", value: 1 }, 
{ source: "Marvin Gaye", target: "Aretha Franklin", value: 1 }, 
{ source: "Ella Fitzgerald", target: "Duke Ellington", value: 1 }, 
{ source: "Prince (musician)", target: "Duke Ellington", value: 1 }, 
{ source: "Frank Sinatra", target: "Duke Ellington", value: 1 }, 
{ source: "Quincy Jones", target: "Duke Ellington", value: 1 }, 
{ source: "Mary J. Blige", target: "Duke Ellington", value: 1 }, 
{ source: "Bing Crosby", target: "Duke Ellington", value: 1 }, 
{ source: "Miles Davis", target: "Duke Ellington", value: 1 }, 
{ source: "Janet Jackson", target: "Marvin Gaye", value: 1 }, 
{ source: "Madonna (entertainer)", target: "Marvin Gaye", value: 1 }, 
{ source: "Diana Ross", target: "Marvin Gaye", value: 1 }, 
{ source: "Stevie Wonder", target: "Marvin Gaye", value: 1 }, 
{ source: "Ray Charles", target: "Marvin Gaye", value: 1 }, 
{ source: "Alicia Keys", target: "Marvin Gaye", value: 1 }, 
{ source: "Barbra Streisand", target: "Marvin Gaye", value: 1 }, 
{ source: "Quincy Jones", target: "Marvin Gaye", value: 1 }, 
{ source: "Jay-Z", target: "Marvin Gaye", value: 1 }, 
{ source: "Mary J. Blige", target: "Marvin Gaye", value: 1 }, 
{ source: "Aretha Franklin", target: "Marvin Gaye", value: 1 }, 
{ source: "Linda Ronstadt", target: "Dolly Parton", value: 1 }, 
{ source: "Emmylou Harris", target: "Dolly Parton", value: 1 }, 
{ source: "Cher", target: "Dolly Parton", value: 1 }, 
{ source: "Whitney Houston", target: "Dolly Parton", value: 1 }, 
{ source: "Rod Stewart", target: "Dolly Parton", value: 1 }, 
{ source: "Ella Fitzgerald", target: "Bing Crosby", value: 1 }, 
{ source: "Ray Charles", target: "Bing Crosby", value: 1 }, 
{ source: "Frank Sinatra", target: "Bing Crosby", value: 1 }, 
{ source: "David Bowie", target: "Bing Crosby", value: 1 }, 
{ source: "Dolly Parton", target: "Linda Ronstadt", value: 1 }, 
{ source: "Ella Fitzgerald", target: "Linda Ronstadt", value: 1 }, 
{ source: "Emmylou Harris", target: "Linda Ronstadt", value: 1 }, 
{ source: "Cher", target: "Linda Ronstadt", value: 1 }, 
{ source: "Barbra Streisand", target: "Linda Ronstadt", value: 1 }, 
{ source: "Neil Young", target: "Linda Ronstadt", value: 1 }, 
{ source: "Joni Mitchell", target: "Linda Ronstadt", value: 1 }, 
{ source: "Bing Crosby", target: "Linda Ronstadt", value: 1 }, 
{ source: "Bob Dylan", target: "David Bowie", value: 1 }, 
{ source: "Cher", target: "David Bowie", value: 1 }, 
{ source: "Frank Sinatra", target: "David Bowie", value: 1 }, 
{ source: "Tina Turner", target: "David Bowie", value: 1 }, 
{ source: "Neil Young", target: "David Bowie", value: 1 }, 
{ source: "John Lennon", target: "David Bowie", value: 1 }, 
{ source: "Eric Clapton", target: "David Bowie", value: 1 }, 
{ source: "Paul McCartney", target: "David Bowie", value: 1 }, 
{ source: "Elton John", target: "David Bowie", value: 1 }, 
{ source: "Bing Crosby", target: "David Bowie", value: 1 }, 
{ source: "Pink Floyd", target: "David Bowie", value: 1 }]}, 
2 : {add: [], del: [{ nodeName: "Nirvana (band)" }, 
{ nodeName: "Billy Joel" }, 
{ nodeName: "Duke Ellington" }], links: [{ source: "Linda Ronstadt", target: "Michael Jackson", value: 1 }, 
{ source: "Dolly Parton", target: "Michael Jackson", value: 1 }, 
{ source: "Janet Jackson", target: "Michael Jackson", value: 1 }, 
{ source: "Mariah Carey", target: "Michael Jackson", value: 1 }, 
{ source: "Madonna (entertainer)", target: "Michael Jackson", value: 1 }, 
{ source: "Diana Ross", target: "Michael Jackson", value: 1 }, 
{ source: "Britney Spears", target: "Michael Jackson", value: 1 }, 
{ source: "Stevie Wonder", target: "Michael Jackson", value: 1 }, 
{ source: "Cher", target: "Michael Jackson", value: 1 }, 
{ source: "Prince (musician)", target: "Michael Jackson", value: 1 }, 
{ source: "Whitney Houston", target: "Michael Jackson", value: 1 }, 
{ source: "Quincy Jones", target: "Michael Jackson", value: 1 }, 
{ source: "Jay-Z", target: "Michael Jackson", value: 1 }, 
{ source: "Neil Young", target: "Michael Jackson", value: 1 }, 
{ source: "Celine Dion", target: "Michael Jackson", value: 1 }, 
{ source: "Paul McCartney", target: "Michael Jackson", value: 1 }, 
{ source: "Bing Crosby", target: "Michael Jackson", value: 1 }, 
{ source: "Marvin Gaye", target: "Michael Jackson", value: 1 }, 
{ source: "The Beatles", target: "Michael Jackson", value: 1 }, 
{ source: "Pink Floyd", target: "Michael Jackson", value: 1 }, 
{ source: "Miles Davis", target: "Michael Jackson", value: 1 }, 
{ source: "Ella Fitzgerald", target: "Chaka Khan", value: 1 }, 
{ source: "Madonna (entertainer)", target: "Chaka Khan", value: 1 }, 
{ source: "Diana Ross", target: "Chaka Khan", value: 1 }, 
{ source: "Stevie Wonder", target: "Chaka Khan", value: 1 }, 
{ source: "Ray Charles", target: "Chaka Khan", value: 1 }, 
{ source: "Cher", target: "Chaka Khan", value: 1 }, 
{ source: "Prince (musician)", target: "Chaka Khan", value: 1 }, 
{ source: "Whitney Houston", target: "Chaka Khan", value: 1 }, 
{ source: "Quincy Jones", target: "Chaka Khan", value: 1 }, 
{ source: "Joni Mitchell", target: "Chaka Khan", value: 1 }, 
{ source: "Eric Clapton", target: "Chaka Khan", value: 1 }, 
{ source: "Mary J. Blige", target: "Chaka Khan", value: 1 }, 
{ source: "Aretha Franklin", target: "Chaka Khan", value: 1 }, 
{ source: "Janet Jackson", target: "Mary J. Blige", value: 1 }, 
{ source: "Chaka Khan", target: "Mary J. Blige", value: 1 }, 
{ source: "Mariah Carey", target: "Mary J. Blige", value: 1 }, 
{ source: "Cher", target: "Mary J. Blige", value: 1 }, 
{ source: "Whitney Houston", target: "Mary J. Blige", value: 1 }, 
{ source: "Jay-Z", target: "Mary J. Blige", value: 1 }, 
{ source: "Celine Dion", target: "Mary J. Blige", value: 1 }, 
{ source: "Sting (musician)", target: "Mary J. Blige", value: 1 }, 
{ source: "Aretha Franklin", target: "Mary J. Blige", value: 1 }, 
{ source: "Marvin Gaye", target: "Mary J. Blige", value: 1 }, 
{ source: "U2", target: "Mary J. Blige", value: 1 }, 
{ source: "Mariah Carey", target: "Kanye West", value: 1 }, 
{ source: "Stevie Wonder", target: "Kanye West", value: 1 }, 
{ source: "Jay-Z", target: "Kanye West", value: 1 }, 
{ source: "Joni Mitchell", target: "Kanye West", value: 1 }, 
{ source: "Sting (musician)", target: "Kanye West", value: 1 }, 
{ source: "Elton John", target: "Kanye West", value: 1 }, 
{ source: "Christina Aguilera", target: "Britney Spears", value: 1 }, 
{ source: "Janet Jackson", target: "Britney Spears", value: 1 }, 
{ source: "Mariah Carey", target: "Britney Spears", value: 1 }, 
{ source: "Madonna (entertainer)", target: "Britney Spears", value: 1 }, 
{ source: "Michael Jackson", target: "Britney Spears", value: 1 }, 
{ source: "Cher", target: "Britney Spears", value: 1 }, 
{ source: "Alicia Keys", target: "Britney Spears", value: 1 }, 
{ source: "Whitney Houston", target: "Britney Spears", value: 1 }, 
{ source: "Kanye West", target: "Britney Spears", value: 1 }, 
{ source: "Linda Ronstadt", target: "Cher", value: 1 }, 
{ source: "Dolly Parton", target: "Cher", value: 1 }, 
{ source: "Christina Aguilera", target: "Cher", value: 1 }, 
{ source: "Janet Jackson", target: "Cher", value: 1 }, 
{ source: "Britney Spears", target: "Cher", value: 1 }, 
{ source: "Whitney Houston", target: "Cher", value: 1 }, 
{ source: "Tina Turner", target: "Cher", value: 1 }, 
{ source: "Barbra Streisand", target: "Cher", value: 1 }, 
{ source: "Celine Dion", target: "Cher", value: 1 }, 
{ source: "Rod Stewart", target: "Cher", value: 1 }, 
{ source: "Linda Ronstadt", target: "Ella Fitzgerald", value: 1 }, 
{ source: "Madonna (entertainer)", target: "Ella Fitzgerald", value: 1 }, 
{ source: "Frank Sinatra", target: "Ella Fitzgerald", value: 1 }, 
{ source: "Barbra Streisand", target: "Ella Fitzgerald", value: 1 }, 
{ source: "Quincy Jones", target: "Ella Fitzgerald", value: 1 }, 
{ source: "Janet Jackson", target: "U2", value: 1 }, 
{ source: "Emmylou Harris", target: "U2", value: 1 }, 
{ source: "Willie Nelson", target: "U2", value: 1 }, 
{ source: "Alicia Keys", target: "U2", value: 1 }, 
{ source: "Tina Turner", target: "U2", value: 1 }, 
{ source: "Bruce Springsteen", target: "U2", value: 1 }, 
{ source: "Quincy Jones", target: "U2", value: 1 }, 
{ source: "Jay-Z", target: "U2", value: 1 }, 
{ source: "Leonard Cohen", target: "U2", value: 1 }, 
{ source: "Celine Dion", target: "U2", value: 1 }, 
{ source: "Paul McCartney", target: "U2", value: 1 }, 
{ source: "Mary J. Blige", target: "U2", value: 1 }, 
{ source: "Kanye West", target: "U2", value: 1 }, 
{ source: "Johnny Cash", target: "U2", value: 1 }, 
{ source: "Pink Floyd", target: "U2", value: 1 }, 
{ source: "The Rolling Stones", target: "U2", value: 1 }, 
{ source: "Linda Ronstadt", target: "Ray Charles", value: 1 }, 
{ source: "Chaka Khan", target: "Ray Charles", value: 1 }, 
{ source: "Elvis Presley", target: "Ray Charles", value: 1 }, 
{ source: "Willie Nelson", target: "Ray Charles", value: 1 }, 
{ source: "Cher", target: "Ray Charles", value: 1 }, 
{ source: "Alicia Keys", target: "Ray Charles", value: 1 }, 
{ source: "Tina Turner", target: "Ray Charles", value: 1 }, 
{ source: "Quincy Jones", target: "Ray Charles", value: 1 }, 
{ source: "Elvis Costello", target: "Ray Charles", value: 1 }, 
{ source: "Elton John", target: "Ray Charles", value: 1 }, 
{ source: "Aretha Franklin", target: "Ray Charles", value: 1 }, 
{ source: "Johnny Cash", target: "Ray Charles", value: 1 }, 
{ source: "Linda Ronstadt", target: "Miles Davis", value: 1 }, 
{ source: "Stevie Wonder", target: "Miles Davis", value: 1 }, 
{ source: "Prince (musician)", target: "Miles Davis", value: 1 }, 
{ source: "Quincy Jones", target: "Miles Davis", value: 1 }, 
{ source: "Joni Mitchell", target: "Miles Davis", value: 1 }, 
{ source: "Sting (musician)", target: "Miles Davis", value: 1 }, 
{ source: "Jimi Hendrix", target: "Miles Davis", value: 1 }, 
{ source: "The Rolling Stones", target: "Miles Davis", value: 1 }, 
{ source: "Janet Jackson", target: "Rod Stewart", value: 1 }, 
{ source: "Diana Ross", target: "Rod Stewart", value: 1 }, 
{ source: "Stevie Wonder", target: "Rod Stewart", value: 1 }, 
{ source: "Cher", target: "Rod Stewart", value: 1 }, 
{ source: "Sting (musician)", target: "Rod Stewart", value: 1 }, 
{ source: "Marvin Gaye", target: "Rod Stewart", value: 1 }, 
{ source: "Linda Ronstadt", target: "Emmylou Harris", value: 1 }, 
{ source: "Dolly Parton", target: "Emmylou Harris", value: 1 }, 
{ source: "Willie Nelson", target: "Emmylou Harris", value: 1 }, 
{ source: "Bruce Springsteen", target: "Emmylou Harris", value: 1 }, 
{ source: "Neil Young", target: "Emmylou Harris", value: 1 }, 
{ source: "Joni Mitchell", target: "Emmylou Harris", value: 1 }, 
{ source: "Linda Ronstadt", target: "Elton John", value: 1 }, 
{ source: "Christina Aguilera", target: "Elton John", value: 1 }, 
{ source: "Janet Jackson", target: "Elton John", value: 1 }, 
{ source: "Mariah Carey", target: "Elton John", value: 1 }, 
{ source: "Stevie Wonder", target: "Elton John", value: 1 }, 
{ source: "Bob Dylan", target: "Elton John", value: 1 }, 
{ source: "Ray Charles", target: "Elton John", value: 1 }, 
{ source: "Cher", target: "Elton John", value: 1 }, 
{ source: "Frank Sinatra", target: "Elton John", value: 1 }, 
{ source: "Tina Turner", target: "Elton John", value: 1 }, 
{ source: "John Lennon", target: "Elton John", value: 1 }, 
{ source: "Rod Stewart", target: "Elton John", value: 1 }, 
{ source: "Eric Clapton", target: "Elton John", value: 1 }, 
{ source: "Elvis Costello", target: "Elton John", value: 1 }, 
{ source: "Aretha Franklin", target: "Elton John", value: 1 }, 
{ source: "Marvin Gaye", target: "Elton John", value: 1 }, 
{ source: "Dolly Parton", target: "Willie Nelson", value: 1 }, 
{ source: "Emmylou Harris", target: "Willie Nelson", value: 1 }, 
{ source: "Bob Dylan", target: "Willie Nelson", value: 1 }, 
{ source: "Ray Charles", target: "Willie Nelson", value: 1 }, 
{ source: "Joni Mitchell", target: "Willie Nelson", value: 1 }, 
{ source: "Elvis Costello", target: "Willie Nelson", value: 1 }, 
{ source: "Johnny Cash", target: "Willie Nelson", value: 1 }, 
{ source: "Linda Ronstadt", target: "John Lennon", value: 1 }, 
{ source: "Dolly Parton", target: "John Lennon", value: 1 }, 
{ source: "Christina Aguilera", target: "John Lennon", value: 1 }, 
{ source: "Madonna (entertainer)", target: "John Lennon", value: 1 }, 
{ source: "Stevie Wonder", target: "John Lennon", value: 1 }, 
{ source: "Bob Dylan", target: "John Lennon", value: 1 }, 
{ source: "Neil Young", target: "John Lennon", value: 1 }, 
{ source: "Celine Dion", target: "John Lennon", value: 1 }, 
{ source: "Eric Clapton", target: "John Lennon", value: 1 }, 
{ source: "Paul McCartney", target: "John Lennon", value: 1 }, 
{ source: "Elton John", target: "John Lennon", value: 1 }, 
{ source: "David Bowie", target: "John Lennon", value: 1 }, 
{ source: "The Beatles", target: "John Lennon", value: 1 }, 
{ source: "Pink Floyd", target: "John Lennon", value: 1 }, 
{ source: "The Rolling Stones", target: "John Lennon", value: 1 }, 
{ source: "Janet Jackson", target: "Eric Clapton", value: 1 }, 
{ source: "Bob Dylan", target: "Eric Clapton", value: 1 }, 
{ source: "Cher", target: "Eric Clapton", value: 1 }, 
{ source: "John Lennon", target: "Eric Clapton", value: 1 }, 
{ source: "Sting (musician)", target: "Eric Clapton", value: 1 }, 
{ source: "Elton John", target: "Eric Clapton", value: 1 }, 
{ source: "Jimi Hendrix", target: "Eric Clapton", value: 1 }, 
{ source: "Johnny Cash", target: "Eric Clapton", value: 1 }, 
{ source: "The Beatles", target: "Eric Clapton", value: 1 }, 
{ source: "Eric Clapton", target: "Pink Floyd", value: 1 }, 
{ source: "Marvin Gaye", target: "Pink Floyd", value: 1 }, 
{ source: "Linda Ronstadt", target: "Elvis Costello", value: 1 }, 
{ source: "Emmylou Harris", target: "Elvis Costello", value: 1 }, 
{ source: "Bruce Springsteen", target: "Elvis Costello", value: 1 }, 
{ source: "Joni Mitchell", target: "Elvis Costello", value: 1 }, 
{ source: "Paul McCartney", target: "Elvis Costello", value: 1 }, 
{ source: "Elton John", target: "Elvis Costello", value: 1 }, 
{ source: "U2", target: "Elvis Costello", value: 1 }, 
{ source: "Stevie Wonder", target: "Paul McCartney", value: 1 }, 
{ source: "Michael Jackson", target: "Paul McCartney", value: 1 }, 
{ source: "Bob Dylan", target: "Paul McCartney", value: 1 }, 
{ source: "Elvis Presley", target: "Paul McCartney", value: 1 }, 
{ source: "Tina Turner", target: "Paul McCartney", value: 1 }, 
{ source: "Jay-Z", target: "Paul McCartney", value: 1 }, 
{ source: "Neil Young", target: "Paul McCartney", value: 1 }, 
{ source: "John Lennon", target: "Paul McCartney", value: 1 }, 
{ source: "Eric Clapton", target: "Paul McCartney", value: 1 }, 
{ source: "Elvis Costello", target: "Paul McCartney", value: 1 }, 
{ source: "Jimi Hendrix", target: "Paul McCartney", value: 1 }, 
{ source: "The Beatles", target: "Paul McCartney", value: 1 }, 
{ source: "Pink Floyd", target: "Paul McCartney", value: 1 }, 
{ source: "Christina Aguilera", target: "Madonna (entertainer)", value: 1 }, 
{ source: "Janet Jackson", target: "Madonna (entertainer)", value: 1 }, 
{ source: "Mariah Carey", target: "Madonna (entertainer)", value: 1 }, 
{ source: "Diana Ross", target: "Madonna (entertainer)", value: 1 }, 
{ source: "Britney Spears", target: "Madonna (entertainer)", value: 1 }, 
{ source: "Michael Jackson", target: "Madonna (entertainer)", value: 1 }, 
{ source: "Elvis Presley", target: "Madonna (entertainer)", value: 1 }, 
{ source: "Cher", target: "Madonna (entertainer)", value: 1 }, 
{ source: "Prince (musician)", target: "Madonna (entertainer)", value: 1 }, 
{ source: "Barbra Streisand", target: "Madonna (entertainer)", value: 1 }, 
{ source: "Joni Mitchell", target: "Madonna (entertainer)", value: 1 }, 
{ source: "Elton John", target: "Madonna (entertainer)", value: 1 }, 
{ source: "Aretha Franklin", target: "Madonna (entertainer)", value: 1 }, 
{ source: "Linda Ronstadt", target: "The Rolling Stones", value: 1 }, 
{ source: "Christina Aguilera", target: "The Rolling Stones", value: 1 }, 
{ source: "Janet Jackson", target: "The Rolling Stones", value: 1 }, 
{ source: "Stevie Wonder", target: "The Rolling Stones", value: 1 }, 
{ source: "Alicia Keys", target: "The Rolling Stones", value: 1 }, 
{ source: "Prince (musician)", target: "The Rolling Stones", value: 1 }, 
{ source: "John Lennon", target: "The Rolling Stones", value: 1 }, 
{ source: "Rod Stewart", target: "The Rolling Stones", value: 1 }, 
{ source: "Eric Clapton", target: "The Rolling Stones", value: 1 }, 
{ source: "Marvin Gaye", target: "The Rolling Stones", value: 1 }, 
{ source: "Jimi Hendrix", target: "The Rolling Stones", value: 1 }, 
{ source: "Kanye West", target: "The Rolling Stones", value: 1 }, 
{ source: "U2", target: "The Rolling Stones", value: 1 }, 
{ source: "The Beatles", target: "The Rolling Stones", value: 1 }, 
{ source: "Miles Davis", target: "The Rolling Stones", value: 1 }, 
{ source: "Emmylou Harris", target: "Jimi Hendrix", value: 1 }, 
{ source: "Bob Dylan", target: "Jimi Hendrix", value: 1 }, 
{ source: "Alicia Keys", target: "Jimi Hendrix", value: 1 }, 
{ source: "Prince (musician)", target: "Jimi Hendrix", value: 1 }, 
{ source: "Rod Stewart", target: "Jimi Hendrix", value: 1 }, 
{ source: "Eric Clapton", target: "Jimi Hendrix", value: 1 }, 
{ source: "Sting (musician)", target: "Jimi Hendrix", value: 1 }, 
{ source: "Pink Floyd", target: "Jimi Hendrix", value: 1 }, 
{ source: "Miles Davis", target: "Jimi Hendrix", value: 1 }, 
{ source: "Joni Mitchell", target: "Leonard Cohen", value: 1 }, 
{ source: "U2", target: "Leonard Cohen", value: 1 }, 
{ source: "Mariah Carey", target: "Jay-Z", value: 1 }, 
{ source: "Britney Spears", target: "Jay-Z", value: 1 }, 
{ source: "Alicia Keys", target: "Jay-Z", value: 1 }, 
{ source: "Mary J. Blige", target: "Jay-Z", value: 1 }, 
{ source: "Kanye West", target: "Jay-Z", value: 1 }, 
{ source: "Linda Ronstadt", target: "Tina Turner", value: 1 }, 
{ source: "Janet Jackson", target: "Tina Turner", value: 1 }, 
{ source: "Cher", target: "Tina Turner", value: 1 }, 
{ source: "Whitney Houston", target: "Tina Turner", value: 1 }, 
{ source: "Joni Mitchell", target: "Tina Turner", value: 1 }, 
{ source: "Celine Dion", target: "Tina Turner", value: 1 }, 
{ source: "Rod Stewart", target: "Tina Turner", value: 1 }, 
{ source: "Eric Clapton", target: "Tina Turner", value: 1 }, 
{ source: "Sting (musician)", target: "Tina Turner", value: 1 }, 
{ source: "Mary J. Blige", target: "Tina Turner", value: 1 }, 
{ source: "David Bowie", target: "Tina Turner", value: 1 }, 
{ source: "Aretha Franklin", target: "Tina Turner", value: 1 }, 
{ source: "U2", target: "Tina Turner", value: 1 }, 
{ source: "Janet Jackson", target: "Bonnie Raitt", value: 1 }, 
{ source: "Emmylou Harris", target: "Bonnie Raitt", value: 1 }, 
{ source: "Willie Nelson", target: "Bonnie Raitt", value: 1 }, 
{ source: "Ray Charles", target: "Bonnie Raitt", value: 1 }, 
{ source: "Christina Aguilera", target: "Janet Jackson", value: 1 }, 
{ source: "Mariah Carey", target: "Janet Jackson", value: 1 }, 
{ source: "Madonna (entertainer)", target: "Janet Jackson", value: 1 }, 
{ source: "Britney Spears", target: "Janet Jackson", value: 1 }, 
{ source: "Michael Jackson", target: "Janet Jackson", value: 1 }, 
{ source: "Whitney Houston", target: "Janet Jackson", value: 1 }, 
{ source: "Joni Mitchell", target: "Janet Jackson", value: 1 }, 
{ source: "Marvin Gaye", target: "Janet Jackson", value: 1 }, 
{ source: "Kanye West", target: "Janet Jackson", value: 1 }, 
{ source: "Dolly Parton", target: "Johnny Cash", value: 1 }, 
{ source: "Emmylou Harris", target: "Johnny Cash", value: 1 }, 
{ source: "Bob Dylan", target: "Johnny Cash", value: 1 }, 
{ source: "Elvis Presley", target: "Johnny Cash", value: 1 }, 
{ source: "Willie Nelson", target: "Johnny Cash", value: 1 }, 
{ source: "Bruce Springsteen", target: "Johnny Cash", value: 1 }, 
{ source: "Neil Young", target: "Johnny Cash", value: 1 }, 
{ source: "U2", target: "Johnny Cash", value: 1 }, 
{ source: "Chaka Khan", target: "Quincy Jones", value: 1 }, 
{ source: "Ella Fitzgerald", target: "Quincy Jones", value: 1 }, 
{ source: "Diana Ross", target: "Quincy Jones", value: 1 }, 
{ source: "Stevie Wonder", target: "Quincy Jones", value: 1 }, 
{ source: "Michael Jackson", target: "Quincy Jones", value: 1 }, 
{ source: "Ray Charles", target: "Quincy Jones", value: 1 }, 
{ source: "Alicia Keys", target: "Quincy Jones", value: 1 }, 
{ source: "Frank Sinatra", target: "Quincy Jones", value: 1 }, 
{ source: "Whitney Houston", target: "Quincy Jones", value: 1 }, 
{ source: "Miles Davis", target: "Quincy Jones", value: 1 }, 
{ source: "Linda Ronstadt", target: "Neil Young", value: 1 }, 
{ source: "Dolly Parton", target: "Neil Young", value: 1 }, 
{ source: "Emmylou Harris", target: "Neil Young", value: 1 }, 
{ source: "Bob Dylan", target: "Neil Young", value: 1 }, 
{ source: "Willie Nelson", target: "Neil Young", value: 1 }, 
{ source: "Whitney Houston", target: "Neil Young", value: 1 }, 
{ source: "Eric Clapton", target: "Neil Young", value: 1 }, 
{ source: "Johnny Cash", target: "Neil Young", value: 1 }, 
{ source: "Miles Davis", target: "Neil Young", value: 1 }, 
{ source: "Janet Jackson", target: "Diana Ross", value: 1 }, 
{ source: "Mariah Carey", target: "Diana Ross", value: 1 }, 
{ source: "Michael Jackson", target: "Diana Ross", value: 1 }, 
{ source: "Cher", target: "Diana Ross", value: 1 }, 
{ source: "Whitney Houston", target: "Diana Ross", value: 1 }, 
{ source: "Rod Stewart", target: "Diana Ross", value: 1 }, 
{ source: "Marvin Gaye", target: "Diana Ross", value: 1 }, 
{ source: "Mariah Carey", target: "Barack Obama", value: 1 }, 
{ source: "Stevie Wonder", target: "Barack Obama", value: 1 }, 
{ source: "Cher", target: "Barack Obama", value: 1 }, 
{ source: "Alicia Keys", target: "Barack Obama", value: 1 }, 
{ source: "Bruce Springsteen", target: "Barack Obama", value: 1 }, 
{ source: "Quincy Jones", target: "Barack Obama", value: 1 }, 
{ source: "Jay-Z", target: "Barack Obama", value: 1 }, 
{ source: "Paul McCartney", target: "Barack Obama", value: 1 }, 
{ source: "Sting (musician)", target: "Barack Obama", value: 1 }, 
{ source: "Mary J. Blige", target: "Barack Obama", value: 1 }, 
{ source: "Aretha Franklin", target: "Barack Obama", value: 1 }, 
{ source: "Kanye West", target: "Barack Obama", value: 1 }, 
{ source: "Linda Ronstadt", target: "Frank Sinatra", value: 1 }, 
{ source: "Ella Fitzgerald", target: "Frank Sinatra", value: 1 }, 
{ source: "Stevie Wonder", target: "Frank Sinatra", value: 1 }, 
{ source: "Elvis Presley", target: "Frank Sinatra", value: 1 }, 
{ source: "Alicia Keys", target: "Frank Sinatra", value: 1 }, 
{ source: "Barbra Streisand", target: "Frank Sinatra", value: 1 }, 
{ source: "Quincy Jones", target: "Frank Sinatra", value: 1 }, 
{ source: "Celine Dion", target: "Frank Sinatra", value: 1 }, 
{ source: "Bing Crosby", target: "Frank Sinatra", value: 1 }, 
{ source: "Linda Ronstadt", target: "Joni Mitchell", value: 1 }, 
{ source: "Janet Jackson", target: "Joni Mitchell", value: 1 }, 
{ source: "Emmylou Harris", target: "Joni Mitchell", value: 1 }, 
{ source: "Bob Dylan", target: "Joni Mitchell", value: 1 }, 
{ source: "Frank Sinatra", target: "Joni Mitchell", value: 1 }, 
{ source: "Prince (musician)", target: "Joni Mitchell", value: 1 }, 
{ source: "Tina Turner", target: "Joni Mitchell", value: 1 }, 
{ source: "Neil Young", target: "Joni Mitchell", value: 1 }, 
{ source: "Leonard Cohen", target: "Joni Mitchell", value: 1 }, 
{ source: "Elvis Costello", target: "Joni Mitchell", value: 1 }, 
{ source: "Janet Jackson", target: "Christina Aguilera", value: 1 }, 
{ source: "Mariah Carey", target: "Christina Aguilera", value: 1 }, 
{ source: "Madonna (entertainer)", target: "Christina Aguilera", value: 1 }, 
{ source: "Britney Spears", target: "Christina Aguilera", value: 1 }, 
{ source: "Cher", target: "Christina Aguilera", value: 1 }, 
{ source: "Alicia Keys", target: "Christina Aguilera", value: 1 }, 
{ source: "Whitney Houston", target: "Christina Aguilera", value: 1 }, 
{ source: "Elvis Costello", target: "Christina Aguilera", value: 1 }, 
{ source: "The Rolling Stones", target: "Christina Aguilera", value: 1 }, 
{ source: "Christina Aguilera", target: "Barbra Streisand", value: 1 }, 
{ source: "Janet Jackson", target: "Barbra Streisand", value: 1 }, 
{ source: "Mariah Carey", target: "Barbra Streisand", value: 1 }, 
{ source: "Madonna (entertainer)", target: "Barbra Streisand", value: 1 }, 
{ source: "Stevie Wonder", target: "Barbra Streisand", value: 1 }, 
{ source: "Elvis Presley", target: "Barbra Streisand", value: 1 }, 
{ source: "Alicia Keys", target: "Barbra Streisand", value: 1 }, 
{ source: "Whitney Houston", target: "Barbra Streisand", value: 1 }, 
{ source: "Celine Dion", target: "Barbra Streisand", value: 1 }, 
{ source: "Madonna (entertainer)", target: "Sting (musician)", value: 1 }, 
{ source: "Stevie Wonder", target: "Sting (musician)", value: 1 }, 
{ source: "Bruce Springsteen", target: "Sting (musician)", value: 1 }, 
{ source: "Rod Stewart", target: "Sting (musician)", value: 1 }, 
{ source: "Elvis Costello", target: "Sting (musician)", value: 1 }, 
{ source: "Mary J. Blige", target: "Sting (musician)", value: 1 }, 
{ source: "Miles Davis", target: "Sting (musician)", value: 1 }, 
{ source: "The Rolling Stones", target: "Sting (musician)", value: 1 }, 
{ source: "Dolly Parton", target: "Elvis Presley", value: 1 }, 
{ source: "Mariah Carey", target: "Elvis Presley", value: 1 }, 
{ source: "Ella Fitzgerald", target: "Elvis Presley", value: 1 }, 
{ source: "Madonna (entertainer)", target: "Elvis Presley", value: 1 }, 
{ source: "Emmylou Harris", target: "Elvis Presley", value: 1 }, 
{ source: "Stevie Wonder", target: "Elvis Presley", value: 1 }, 
{ source: "Michael Jackson", target: "Elvis Presley", value: 1 }, 
{ source: "Bob Dylan", target: "Elvis Presley", value: 1 }, 
{ source: "Ray Charles", target: "Elvis Presley", value: 1 }, 
{ source: "Cher", target: "Elvis Presley", value: 1 }, 
{ source: "Frank Sinatra", target: "Elvis Presley", value: 1 }, 
{ source: "Tina Turner", target: "Elvis Presley", value: 1 }, 
{ source: "Bruce Springsteen", target: "Elvis Presley", value: 1 }, 
{ source: "Barbra Streisand", target: "Elvis Presley", value: 1 }, 
{ source: "Neil Young", target: "Elvis Presley", value: 1 }, 
{ source: "Celine Dion", target: "Elvis Presley", value: 1 }, 
{ source: "John Lennon", target: "Elvis Presley", value: 1 }, 
{ source: "Paul McCartney", target: "Elvis Presley", value: 1 }, 
{ source: "Elvis Costello", target: "Elvis Presley", value: 1 }, 
{ source: "Elton John", target: "Elvis Presley", value: 1 }, 
{ source: "Bing Crosby", target: "Elvis Presley", value: 1 }, 
{ source: "David Bowie", target: "Elvis Presley", value: 1 }, 
{ source: "Jimi Hendrix", target: "Elvis Presley", value: 1 }, 
{ source: "Johnny Cash", target: "Elvis Presley", value: 1 }, 
{ source: "U2", target: "Elvis Presley", value: 1 }, 
{ source: "The Beatles", target: "Elvis Presley", value: 1 }, 
{ source: "Chaka Khan", target: "Stevie Wonder", value: 1 }, 
{ source: "Mariah Carey", target: "Stevie Wonder", value: 1 }, 
{ source: "Ella Fitzgerald", target: "Stevie Wonder", value: 1 }, 
{ source: "Diana Ross", target: "Stevie Wonder", value: 1 }, 
{ source: "Michael Jackson", target: "Stevie Wonder", value: 1 }, 
{ source: "Alicia Keys", target: "Stevie Wonder", value: 1 }, 
{ source: "Prince (musician)", target: "Stevie Wonder", value: 1 }, 
{ source: "Whitney Houston", target: "Stevie Wonder", value: 1 }, 
{ source: "Barbra Streisand", target: "Stevie Wonder", value: 1 }, 
{ source: "Quincy Jones", target: "Stevie Wonder", value: 1 }, 
{ source: "John Lennon", target: "Stevie Wonder", value: 1 }, 
{ source: "Rod Stewart", target: "Stevie Wonder", value: 1 }, 
{ source: "Paul McCartney", target: "Stevie Wonder", value: 1 }, 
{ source: "Sting (musician)", target: "Stevie Wonder", value: 1 }, 
{ source: "Elton John", target: "Stevie Wonder", value: 1 }, 
{ source: "Mary J. Blige", target: "Stevie Wonder", value: 1 }, 
{ source: "Aretha Franklin", target: "Stevie Wonder", value: 1 }, 
{ source: "Marvin Gaye", target: "Stevie Wonder", value: 1 }, 
{ source: "Janet Jackson", target: "Prince (musician)", value: 1 }, 
{ source: "Chaka Khan", target: "Prince (musician)", value: 1 }, 
{ source: "Madonna (entertainer)", target: "Prince (musician)", value: 1 }, 
{ source: "Bonnie Raitt", target: "Prince (musician)", value: 1 }, 
{ source: "Stevie Wonder", target: "Prince (musician)", value: 1 }, 
{ source: "Bob Dylan", target: "Prince (musician)", value: 1 }, 
{ source: "Alicia Keys", target: "Prince (musician)", value: 1 }, 
{ source: "Joni Mitchell", target: "Prince (musician)", value: 1 }, 
{ source: "Marvin Gaye", target: "Prince (musician)", value: 1 }, 
{ source: "Jimi Hendrix", target: "Prince (musician)", value: 1 }, 
{ source: "Miles Davis", target: "Prince (musician)", value: 1 }, 
{ source: "Christina Aguilera", target: "Alicia Keys", value: 1 }, 
{ source: "Janet Jackson", target: "Alicia Keys", value: 1 }, 
{ source: "Diana Ross", target: "Alicia Keys", value: 1 }, 
{ source: "Prince (musician)", target: "Alicia Keys", value: 1 }, 
{ source: "Whitney Houston", target: "Alicia Keys", value: 1 }, 
{ source: "David Bowie", target: "Alicia Keys", value: 1 }, 
{ source: "Kanye West", target: "Alicia Keys", value: 1 }, 
{ source: "Christina Aguilera", target: "Mariah Carey", value: 1 }, 
{ source: "Janet Jackson", target: "Mariah Carey", value: 1 }, 
{ source: "Michael Jackson", target: "Mariah Carey", value: 1 }, 
{ source: "Elvis Presley", target: "Mariah Carey", value: 1 }, 
{ source: "Cher", target: "Mariah Carey", value: 1 }, 
{ source: "Whitney Houston", target: "Mariah Carey", value: 1 }, 
{ source: "Jay-Z", target: "Mariah Carey", value: 1 }, 
{ source: "Celine Dion", target: "Mariah Carey", value: 1 }, 
{ source: "Sting (musician)", target: "Mariah Carey", value: 1 }, 
{ source: "Dolly Parton", target: "Whitney Houston", value: 1 }, 
{ source: "Christina Aguilera", target: "Whitney Houston", value: 1 }, 
{ source: "Janet Jackson", target: "Whitney Houston", value: 1 }, 
{ source: "Mariah Carey", target: "Whitney Houston", value: 1 }, 
{ source: "Diana Ross", target: "Whitney Houston", value: 1 }, 
{ source: "Britney Spears", target: "Whitney Houston", value: 1 }, 
{ source: "Stevie Wonder", target: "Whitney Houston", value: 1 }, 
{ source: "Michael Jackson", target: "Whitney Houston", value: 1 }, 
{ source: "Cher", target: "Whitney Houston", value: 1 }, 
{ source: "Alicia Keys", target: "Whitney Houston", value: 1 }, 
{ source: "Barbra Streisand", target: "Whitney Houston", value: 1 }, 
{ source: "Celine Dion", target: "Whitney Houston", value: 1 }, 
{ source: "Sting (musician)", target: "Whitney Houston", value: 1 }, 
{ source: "Mary J. Blige", target: "Whitney Houston", value: 1 }, 
{ source: "Aretha Franklin", target: "Whitney Houston", value: 1 }, 
{ source: "Linda Ronstadt", target: "Bob Dylan", value: 1 }, 
{ source: "Emmylou Harris", target: "Bob Dylan", value: 1 }, 
{ source: "Stevie Wonder", target: "Bob Dylan", value: 1 }, 
{ source: "Elvis Presley", target: "Bob Dylan", value: 1 }, 
{ source: "Willie Nelson", target: "Bob Dylan", value: 1 }, 
{ source: "Cher", target: "Bob Dylan", value: 1 }, 
{ source: "Frank Sinatra", target: "Bob Dylan", value: 1 }, 
{ source: "Prince (musician)", target: "Bob Dylan", value: 1 }, 
{ source: "Bruce Springsteen", target: "Bob Dylan", value: 1 }, 
{ source: "Neil Young", target: "Bob Dylan", value: 1 }, 
{ source: "Joni Mitchell", target: "Bob Dylan", value: 1 }, 
{ source: "John Lennon", target: "Bob Dylan", value: 1 }, 
{ source: "Rod Stewart", target: "Bob Dylan", value: 1 }, 
{ source: "Eric Clapton", target: "Bob Dylan", value: 1 }, 
{ source: "Paul McCartney", target: "Bob Dylan", value: 1 }, 
{ source: "Sting (musician)", target: "Bob Dylan", value: 1 }, 
{ source: "Jimi Hendrix", target: "Bob Dylan", value: 1 }, 
{ source: "Johnny Cash", target: "Bob Dylan", value: 1 }, 
{ source: "U2", target: "Bob Dylan", value: 1 }, 
{ source: "The Beatles", target: "Bob Dylan", value: 1 }, 
{ source: "The Rolling Stones", target: "Bob Dylan", value: 1 }, 
{ source: "Linda Ronstadt", target: "Bruce Springsteen", value: 1 }, 
{ source: "Janet Jackson", target: "Bruce Springsteen", value: 1 }, 
{ source: "Bonnie Raitt", target: "Bruce Springsteen", value: 1 }, 
{ source: "Emmylou Harris", target: "Bruce Springsteen", value: 1 }, 
{ source: "Stevie Wonder", target: "Bruce Springsteen", value: 1 }, 
{ source: "Bob Dylan", target: "Bruce Springsteen", value: 1 }, 
{ source: "Neil Young", target: "Bruce Springsteen", value: 1 }, 
{ source: "Sting (musician)", target: "Bruce Springsteen", value: 1 }, 
{ source: "Elvis Costello", target: "Bruce Springsteen", value: 1 }, 
{ source: "U2", target: "Bruce Springsteen", value: 1 }, 
{ source: "Christina Aguilera", target: "Celine Dion", value: 1 }, 
{ source: "Mariah Carey", target: "Celine Dion", value: 1 }, 
{ source: "Cher", target: "Celine Dion", value: 1 }, 
{ source: "Whitney Houston", target: "Celine Dion", value: 1 }, 
{ source: "Barbra Streisand", target: "Celine Dion", value: 1 }, 
{ source: "Quincy Jones", target: "Celine Dion", value: 1 }, 
{ source: "Elton John", target: "Celine Dion", value: 1 }, 
{ source: "Mariah Carey", target: "The Beatles", value: 1 }, 
{ source: "Madonna (entertainer)", target: "The Beatles", value: 1 }, 
{ source: "Emmylou Harris", target: "The Beatles", value: 1 }, 
{ source: "Michael Jackson", target: "The Beatles", value: 1 }, 
{ source: "Bob Dylan", target: "The Beatles", value: 1 }, 
{ source: "Elvis Presley", target: "The Beatles", value: 1 }, 
{ source: "Frank Sinatra", target: "The Beatles", value: 1 }, 
{ source: "Prince (musician)", target: "The Beatles", value: 1 }, 
{ source: "Whitney Houston", target: "The Beatles", value: 1 }, 
{ source: "Barbra Streisand", target: "The Beatles", value: 1 }, 
{ source: "Celine Dion", target: "The Beatles", value: 1 }, 
{ source: "John Lennon", target: "The Beatles", value: 1 }, 
{ source: "Rod Stewart", target: "The Beatles", value: 1 }, 
{ source: "Eric Clapton", target: "The Beatles", value: 1 }, 
{ source: "Paul McCartney", target: "The Beatles", value: 1 }, 
{ source: "Elvis Costello", target: "The Beatles", value: 1 }, 
{ source: "Elton John", target: "The Beatles", value: 1 }, 
{ source: "Bing Crosby", target: "The Beatles", value: 1 }, 
{ source: "Jimi Hendrix", target: "The Beatles", value: 1 }, 
{ source: "U2", target: "The Beatles", value: 1 }, 
{ source: "Pink Floyd", target: "The Beatles", value: 1 }, 
{ source: "Christina Aguilera", target: "Aretha Franklin", value: 1 }, 
{ source: "Mariah Carey", target: "Aretha Franklin", value: 1 }, 
{ source: "Ella Fitzgerald", target: "Aretha Franklin", value: 1 }, 
{ source: "Stevie Wonder", target: "Aretha Franklin", value: 1 }, 
{ source: "Whitney Houston", target: "Aretha Franklin", value: 1 }, 
{ source: "Barbra Streisand", target: "Aretha Franklin", value: 1 }, 
{ source: "Celine Dion", target: "Aretha Franklin", value: 1 }, 
{ source: "Mary J. Blige", target: "Aretha Franklin", value: 1 }, 
{ source: "Marvin Gaye", target: "Aretha Franklin", value: 1 }, 
{ source: "Janet Jackson", target: "Marvin Gaye", value: 1 }, 
{ source: "Madonna (entertainer)", target: "Marvin Gaye", value: 1 }, 
{ source: "Diana Ross", target: "Marvin Gaye", value: 1 }, 
{ source: "Stevie Wonder", target: "Marvin Gaye", value: 1 }, 
{ source: "Ray Charles", target: "Marvin Gaye", value: 1 }, 
{ source: "Alicia Keys", target: "Marvin Gaye", value: 1 }, 
{ source: "Barbra Streisand", target: "Marvin Gaye", value: 1 }, 
{ source: "Quincy Jones", target: "Marvin Gaye", value: 1 }, 
{ source: "Jay-Z", target: "Marvin Gaye", value: 1 }, 
{ source: "Mary J. Blige", target: "Marvin Gaye", value: 1 }, 
{ source: "Aretha Franklin", target: "Marvin Gaye", value: 1 }, 
{ source: "Linda Ronstadt", target: "Dolly Parton", value: 1 }, 
{ source: "Emmylou Harris", target: "Dolly Parton", value: 1 }, 
{ source: "Cher", target: "Dolly Parton", value: 1 }, 
{ source: "Whitney Houston", target: "Dolly Parton", value: 1 }, 
{ source: "Rod Stewart", target: "Dolly Parton", value: 1 }, 
{ source: "Ella Fitzgerald", target: "Bing Crosby", value: 1 }, 
{ source: "Ray Charles", target: "Bing Crosby", value: 1 }, 
{ source: "Frank Sinatra", target: "Bing Crosby", value: 1 }, 
{ source: "David Bowie", target: "Bing Crosby", value: 1 }, 
{ source: "Dolly Parton", target: "Linda Ronstadt", value: 1 }, 
{ source: "Ella Fitzgerald", target: "Linda Ronstadt", value: 1 }, 
{ source: "Emmylou Harris", target: "Linda Ronstadt", value: 1 }, 
{ source: "Cher", target: "Linda Ronstadt", value: 1 }, 
{ source: "Barbra Streisand", target: "Linda Ronstadt", value: 1 }, 
{ source: "Neil Young", target: "Linda Ronstadt", value: 1 }, 
{ source: "Joni Mitchell", target: "Linda Ronstadt", value: 1 }, 
{ source: "Bing Crosby", target: "Linda Ronstadt", value: 1 }, 
{ source: "Bob Dylan", target: "David Bowie", value: 1 }, 
{ source: "Cher", target: "David Bowie", value: 1 }, 
{ source: "Frank Sinatra", target: "David Bowie", value: 1 }, 
{ source: "Tina Turner", target: "David Bowie", value: 1 }, 
{ source: "Neil Young", target: "David Bowie", value: 1 }, 
{ source: "John Lennon", target: "David Bowie", value: 1 }, 
{ source: "Eric Clapton", target: "David Bowie", value: 1 }, 
{ source: "Paul McCartney", target: "David Bowie", value: 1 }, 
{ source: "Elton John", target: "David Bowie", value: 1 }, 
{ source: "Bing Crosby", target: "David Bowie", value: 1 }, 
{ source: "Pink Floyd", target: "David Bowie", value: 1 }]}};
