var miserables2010 = {
nodes: [
{nodeName: "Michael Jackson"}, 
{nodeName: "Taio Cruz"}, 
{nodeName: "La Toya Jackson"}, 
{nodeName: "Den Harrow"}, 
{nodeName: "Kim Wilde"}, 
{nodeName: "Prince"}, 
{nodeName: "Patti Austin"}, 
{nodeName: "Darren Hayes"}, 
{nodeName: "Natalie Gauci"}, 
{nodeName: "Cher (Künstlerin)"}, 
{nodeName: "Harry Belafonte"}, 
{nodeName: "Michael Sembello"}, 
{nodeName: "Bill Withers"}, 
{nodeName: "Rolf Stahlhofen"}, 
{nodeName: "Fancy"}, 
{nodeName: "Silvy de Bie"}, 
{nodeName: "Randy Jackson"}, 
{nodeName: "Marc Terenzi"}, 
{nodeName: "Adam Lambert"}, 
{nodeName: "Tito Jackson"}, 
{nodeName: "Rebbie Jackson"}, 
{nodeName: "Pia Zadora"}, 
{nodeName: "Lionel Richie"}, 
{nodeName: "Madonna (Künstlerin)"}, 
{nodeName: "Sarah Connor"}, 
{nodeName: "Nerina Pallot"}, 
{nodeName: "Lisa Marie Presley"}, 
{nodeName: "Jarvis Cocker"}, 
{nodeName: "Giovanni Zarrella"}, 
{nodeName: "Janet Jackson"}, 
{nodeName: "Céline Dion"}, 
{nodeName: "Tomomi Kahala"}, 
{nodeName: "Albano Carrisi"}, 
{nodeName: "Kenny Loggins"}, 
{nodeName: "Zeeteah"}, 
{nodeName: "Bob Gaudio"}, 
{nodeName: "Jennifer Hudson"}, 
{nodeName: "DJ BoBo"}, 
{nodeName: "Stéphanie von Monaco"}, 
{nodeName: "Sharon Cuneta"}, 
{nodeName: "Mai Kuraki"}, 
{nodeName: "Nisha Kataria"}, 
{nodeName: "Diana Ross"}, 
{nodeName: "Jermaine Jackson"}, 
{nodeName: "Stevie Wonder"}, 
{nodeName: "Rockwell (Musiker)"}, 
{nodeName: "Fergie (Sängerin)"}, 
{nodeName: "Mariah Carey"}, 
{nodeName: "David Bowie"}
], links:[
{source: 1, target: 0, value: 2}, 
{source: 2, target: 0, value: 2}, 
{source: 3, target: 0, value: 2}, 
{source: 4, target: 0, value: 2}, 
{source: 5, target: 0, value: 2}, 
{source: 6, target: 0, value: 2}, 
{source: 7, target: 0, value: 2}, 
{source: 8, target: 0, value: 2}, 
{source: 9, target: 0, value: 2}, 
{source: 10, target: 0, value: 2}, 
{source: 11, target: 0, value: 2}, 
{source: 12, target: 0, value: 2}, 
{source: 13, target: 0, value: 2}, 
{source: 14, target: 0, value: 2}, 
{source: 15, target: 0, value: 2}, 
{source: 16, target: 0, value: 2}, 
{source: 17, target: 0, value: 2}, 
{source: 18, target: 0, value: 2}, 
{source: 19, target: 0, value: 2}, 
{source: 20, target: 0, value: 2}, 
{source: 21, target: 0, value: 2}, 
{source: 22, target: 0, value: 2}, 
{source: 23, target: 0, value: 2}, 
{source: 24, target: 0, value: 2}, 
{source: 25, target: 0, value: 2}, 
{source: 26, target: 0, value: 2}, 
{source: 27, target: 0, value: 2}, 
{source: 28, target: 0, value: 2}, 
{source: 29, target: 0, value: 2}, 
{source: 30, target: 0, value: 2}, 
{source: 31, target: 0, value: 2}, 
{source: 32, target: 0, value: 2}, 
{source: 33, target: 0, value: 2}, 
{source: 34, target: 0, value: 2}, 
{source: 35, target: 0, value: 2}, 
{source: 36, target: 0, value: 2}, 
{source: 37, target: 0, value: 2}, 
{source: 38, target: 0, value: 2}, 
{source: 39, target: 0, value: 2}, 
{source: 40, target: 0, value: 2}, 
{source: 41, target: 0, value: 2}, 
{source: 42, target: 0, value: 2}, 
{source: 43, target: 0, value: 2}, 
{source: 44, target: 0, value: 2}, 
{source: 45, target: 0, value: 2}, 
{source: 46, target: 0, value: 2}, 
{source: 47, target: 0, value: 2}, 
{source: 48, target: 0, value: 2}
] };

var newStringLinks = [ 
{source: "Taio Cruz", target: "Michael Jackson", value: 2},
{source: "La Toya Jackson", target: "Michael Jackson", value: 2},
{source: "Den Harrow", target: "Michael Jackson", value: 2},
{source: "Kim Wilde", target: "Michael Jackson", value: 2},
{source: "Patti Austin", target: "Michael Jackson", value: 2},
{source: "Darren Hayes", target: "Michael Jackson", value: 2},
{source: "Natalie Gauci", target: "Michael Jackson", value: 2},
{source: "Harry Belafonte", target: "Michael Jackson", value: 2},
{source: "Cher (Künstlerin)", target: "Michael Jackson", value: 2},
{source: "Bill Withers", target: "Michael Jackson", value: 2},
{source: "Michael Sembello", target: "Michael Jackson", value: 2},
{source: "Fancy", target: "Michael Jackson", value: 2},
{source: "Silvy de Bie", target: "Michael Jackson", value: 2},
{source: "Randy Jackson", target: "Michael Jackson", value: 2},
{source: "Marc Terenzi", target: "Michael Jackson", value: 2},
{source: "Tito Jackson", target: "Michael Jackson", value: 2},
{source: "Rebbie Jackson", target: "Michael Jackson", value: 2},
{source: "Pia Zadora", target: "Michael Jackson", value: 2},
{source: "Lionel Richie", target: "Michael Jackson", value: 2},
{source: "Madonna (Künstlerin)", target: "Michael Jackson", value: 2},
{source: "Sarah Connor", target: "Michael Jackson", value: 2},
{source: "Lisa Marie Presley", target: "Michael Jackson", value: 2},
{source: "Nerina Pallot", target: "Michael Jackson", value: 2},
{source: "Prince", target: "Michael Jackson", value: 2},
{source: "Jarvis Cocker", target: "Michael Jackson", value: 2},
//{source: "Janet Jackson", target: "Michael Jackson", value: 2},
{source: "Céline Dion", target: "Michael Jackson", value: 2},
{source: "Tomomi Kahala", target: "Michael Jackson", value: 2},
{source: "Kenny Loggins", target: "Michael Jackson", value: 2},
{source: "Zeeteah", target: "Michael Jackson", value: 2},
{source: "Bob Gaudio", target: "Michael Jackson", value: 2},
{source: "DJ BoBo", target: "Michael Jackson", value: 2},
{source: "DJ BoBo", target: "Céline Dion", value: 2},
{source: "Sharon Cuneta", target: "Michael Jackson", value: 2},
{source: "Mai Kuraki", target: "Michael Jackson", value: 2},
{source: "Nisha Kataria", target: "Michael Jackson", value: 2},
{source: "Jermaine Jackson", target: "Michael Jackson", value: 2},
{source: "Stevie Wonder", target: "Michael Jackson", value: 2},
{source: "Rockwell (Musiker)", target: "Michael Jackson", value: 2},
{source: "David Bowie", target: "Michael Jackson", value: 2}
];

var newStringLinks2 = [ 
{source: "Taio Cruz", target: "Michael Jackson", value: 2},
{source: "La Toya Jackson", target: "Michael Jackson", value: 2},
{source: "Den Harrow", target: "Michael Jackson", value: 2},
{source: "Kim Wilde", target: "Michael Jackson", value: 2},
{source: "Patti Austin", target: "Michael Jackson", value: 2},
{source: "Darren Hayes", target: "Michael Jackson", value: 2},
{source: "Natalie Gauci", target: "Michael Jackson", value: 2},
{source: "Harry Belafonte", target: "Michael Jackson", value: 2},
{source: "Cher (Künstlerin)", target: "Michael Jackson", value: 2},
{source: "Bill Withers", target: "Michael Jackson", value: 2},
{source: "Michael Sembello", target: "Michael Jackson", value: 2},
{source: "Fancy", target: "Michael Jackson", value: 2},
{source: "Silvy de Bie", target: "Michael Jackson", value: 2},
{source: "Randy Jackson", target: "Michael Jackson", value: 2},
{source: "Marc Terenzi", target: "Michael Jackson", value: 2},
{source: "Tito Jackson", target: "Michael Jackson", value: 2},
{source: "Rebbie Jackson", target: "Michael Jackson", value: 2},
{source: "Pia Zadora", target: "Michael Jackson", value: 2},
{source: "Lionel Richie", target: "Michael Jackson", value: 2},
{source: "Madonna (Künstlerin)", target: "Michael Jackson", value: 2},
{source: "Sarah Connor", target: "Michael Jackson", value: 2},
{source: "Lisa Marie Presley", target: "Michael Jackson", value: 2},
{source: "Nerina Pallot", target: "Michael Jackson", value: 2},
{source: "Prince", target: "Michael Jackson", value: 2},
{source: "Jarvis Cocker", target: "Michael Jackson", value: 2},
//{source: "Janet Jackson", target: "Michael Jackson", value: 2},
{source: "Céline Dion", target: "Michael Jackson", value: 2},
{source: "Tomomi Kahala", target: "Michael Jackson", value: 2},
{source: "Kenny Loggins", target: "Michael Jackson", value: 2},
{source: "Zeeteah", target: "Michael Jackson", value: 2},
{source: "Bob Gaudio", target: "Michael Jackson", value: 2},
{source: "DJ BoBo", target: "Michael Jackson", value: 2},
{source: "DJ BoBo", target: "Céline Dion", value: 2},
{source: "Sharon Cuneta", target: "Michael Jackson", value: 2},
{source: "Mai Kuraki", target: "Michael Jackson", value: 2},
{source: "Nisha Kataria", target: "Michael Jackson", value: 2},
{source: "Nisha Kataria", target: "Céline Dion", value: 2},
{source: "Jermaine Jackson", target: "Michael Jackson", value: 2},
{source: "Jermaine Jackson", target: "Céline Dion", value: 2},
{source: "Stevie Wonder", target: "Michael Jackson", value: 2},
{source: "Rockwell (Musiker)", target: "Michael Jackson", value: 2},
{source: "David Bowie", target: "Michael Jackson", value: 2},
{source: "TEST 2nd Frame", target: "Céline Dion", value: 2}
];

var addList = [
               {nodeName: "Prince"}, 
               {nodeName: "Nerina Pallot"},
               {nodeName: "Giovanni Zarrella"},
               {nodeName: "Albano Carrisi"},
               {nodeName: "Jennifer Hudson"},
               {nodeName: "Stéphanie von Monaco"},
               {nodeName: "Diana Ross"},
               {nodeName: "Mariah Carey"},
               {nodeName: "Adam Lambert"}
               ];

			var addList2 = [
			               {nodeName: "TEST 2nd Frame"}
			               
			               ];
               
var delList = [
               {nodeName: "Janet Jackson"}
               ];