var miserables2011 = {
nodes: [
{nodeName: "Michael Jackson"}, 
{nodeName: "La Toya Jackson"}, 
{nodeName: "Den Harrow"}, 
{nodeName: "Kim Wilde"}, 
{nodeName: "Patti Austin"}, 
{nodeName: "Cher (Künstlerin)"}, 
{nodeName: "Lady Gaga"}, 
{nodeName: "Rebbie Jackson"}, 
{nodeName: "Madonna (Künstlerin)"}, 
{nodeName: "Sarah Connor"}, 
{nodeName: "Lisa Marie Presley"}, 
{nodeName: "Nerina Pallot"}, 
{nodeName: "Jarvis Cocker"}, 
{nodeName: "Giovanni Zarrella"}, 
{nodeName: "Tomomi Kahala"}, 
{nodeName: "Albano Carrisi"}, 
{nodeName: "Kenny Loggins"}, 
{nodeName: "Zeeteah"}, 
{nodeName: "Jennifer Hudson"}, 
{nodeName: "Sharon Cuneta"}, 
{nodeName: "Mai Kuraki"}, 
{nodeName: "Diana Ross"}, 
{nodeName: "Rockwell (Musiker)"}, 
{nodeName: "Mariah Carey"}, 
{nodeName: "Taio Cruz"}, 
{nodeName: "Darren Hayes"}, 
{nodeName: "Prince"}, 
{nodeName: "Natalie Gauci"}, 
{nodeName: "Harry Belafonte"}, 
{nodeName: "Bill Withers"}, 
{nodeName: "Michael Sembello"}, 
{nodeName: "Rolf Stahlhofen"}, 
{nodeName: "Fancy"}, 
{nodeName: "Silvy de Bie"}, 
{nodeName: "Adam Lambert"}, 
{nodeName: "Marc Terenzi"}, 
{nodeName: "Randy Jackson"}, 
{nodeName: "Tito Jackson"}, 
{nodeName: "Lionel Richie"}, 
{nodeName: "Pia Zadora"}, 
{nodeName: "Letta Mbulu"}, 
{nodeName: "Janet Jackson"}, 
{nodeName: "Donna Summer"}, 
{nodeName: "Céline Dion"}, 
{nodeName: "Bob Gaudio"}, 
{nodeName: "DJ BoBo"}, 
{nodeName: "Brandy"}, 
{nodeName: "Stéphanie von Monaco"}, 
{nodeName: "Nisha Kataria"}, 
{nodeName: "Jermaine Jackson"}, 
{nodeName: "Stevie Wonder"}, 
{nodeName: "Menowin Fröhlich"}, 
{nodeName: "Fergie (Sängerin)"}, 
{nodeName: "David Bowie"}, 
{nodeName: "Kylie Minogue"}, 
{nodeName: "Jem"}, 
{nodeName: "Nikos Karvelas"}, 
{nodeName: "Laura White"}, 
{nodeName: "Stacey Q"}, 
{nodeName: "Kalomoira"}, 
{nodeName: "Meg Pfeiffer"}, 
{nodeName: "Nick Kamen"}, 
{nodeName: "Britney Spears"}, 
{nodeName: "Johan Renck"}, 
{nodeName: "Jimmy Nail"}, 
{nodeName: "Greyson Michael Chance"}, 
{nodeName: "Patrick Hernandez"}, 
{nodeName: "Sertab Erener"}, 
{nodeName: "Safura"}, 
{nodeName: "Michael Davidson (Sänger)"}, 
{nodeName: "Selena Quintanilla-Pérez"}, 
{nodeName: "Annie Lennox"}, 
{nodeName: "Robyn"}, 
{nodeName: "Selena Gomez"}, 
{nodeName: "Kelly Osbourne"}, 
{nodeName: "Carole King"}, 
{nodeName: "Alizée"}, 
{nodeName: "Étienne Daho"}, 
{nodeName: "Shakira"}, 
{nodeName: "Leila K."}, 
{nodeName: "Rollergirl"}, 
{nodeName: "Christina Aguilera"}, 
{nodeName: "Whitney Houston"}, 
{nodeName: "Hila Bronstein"}, 
{nodeName: "AnNa R."}, 
{nodeName: "Leon Jackson"}, 
{nodeName: "Dana Dawson"}, 
{nodeName: "Stacie Orrico"}, 
{nodeName: "Glennis Grace"}, 
{nodeName: "Juliette Schoppmann"}, 
{nodeName: "Mira Craig"}, 
{nodeName: "Gerry Goffin"}, 
{nodeName: "Lia Weller"}, 
{nodeName: "Phyllis Hyman"}, 
{nodeName: "JoJo"}, 
{nodeName: "Jolin Tsai"}, 
{nodeName: "Chaka Khan"}, 
{nodeName: "George Michael"}, 
{nodeName: "Elisa Toffoli"}, 
{nodeName: "Dionne Warwick"}, 
{nodeName: "Albert Hammond"}, 
{nodeName: "Monika Ivkic"}, 
{nodeName: "Cornelia Mooswalder"}, 
{nodeName: "Thea Garrett"}, 
{nodeName: "Alexis (Sängerin)"}
], links:[
{source: 1, target: 0, value: 2}, 
{source: 2, target: 0, value: 2}, 
{source: 3, target: 0, value: 2}, 
{source: 4, target: 0, value: 2}, 
{source: 5, target: 0, value: 2}, 
{source: 6, target: 0, value: 2}, 
{source: 7, target: 0, value: 2}, 
{source: 8, target: 0, value: 2}, 
{source: 9, target: 0, value: 2}, 
{source: 10, target: 0, value: 2}, 
{source: 11, target: 0, value: 2}, 
{source: 12, target: 0, value: 2}, 
{source: 13, target: 0, value: 2}, 
{source: 14, target: 0, value: 2}, 
{source: 15, target: 0, value: 2}, 
{source: 16, target: 0, value: 2}, 
{source: 17, target: 0, value: 2}, 
{source: 18, target: 0, value: 2}, 
{source: 19, target: 0, value: 2}, 
{source: 20, target: 0, value: 2}, 
{source: 21, target: 0, value: 2}, 
{source: 22, target: 0, value: 2}, 
{source: 23, target: 0, value: 2}, 
{source: 24, target: 0, value: 2}, 
{source: 25, target: 0, value: 2}, 
{source: 26, target: 0, value: 2}, 
{source: 27, target: 0, value: 2}, 
{source: 28, target: 0, value: 2}, 
{source: 29, target: 0, value: 2}, 
{source: 30, target: 0, value: 2}, 
{source: 31, target: 0, value: 2}, 
{source: 32, target: 0, value: 2}, 
{source: 33, target: 0, value: 2}, 
{source: 34, target: 0, value: 2}, 
{source: 35, target: 0, value: 2}, 
{source: 36, target: 0, value: 2}, 
{source: 37, target: 0, value: 2}, 
{source: 38, target: 0, value: 2}, 
{source: 39, target: 0, value: 2}, 
{source: 40, target: 0, value: 2}, 
{source: 41, target: 0, value: 2}, 
{source: 42, target: 0, value: 2}, 
{source: 43, target: 0, value: 2}, 
{source: 44, target: 0, value: 2}, 
{source: 45, target: 0, value: 2}, 
{source: 46, target: 0, value: 2}, 
{source: 47, target: 0, value: 2}, 
{source: 48, target: 0, value: 2}, 
{source: 49, target: 0, value: 2}, 
{source: 50, target: 0, value: 2}, 
{source: 51, target: 0, value: 2}, 
{source: 52, target: 0, value: 2}, 
{source: 53, target: 0, value: 2}, 
{source: 54, target: 8, value: 2}, 
{source: 55, target: 8, value: 2}, 
{source: 56, target: 8, value: 2}, 
{source: 57, target: 8, value: 2}, 
{source: 58, target: 8, value: 2}, 
{source: 26, target: 8, value: 2}, 
{source: 27, target: 8, value: 2}, 
{source: 6, target: 8, value: 2}, 
{source: 31, target: 8, value: 2}, 
{source: 59, target: 8, value: 2}, 
{source: 60, target: 8, value: 2}, 
{source: 61, target: 8, value: 2}, 
{source: 62, target: 8, value: 2}, 
{source: 63, target: 8, value: 2}, 
{source: 64, target: 8, value: 2}, 
{source: 65, target: 8, value: 2}, 
{source: 66, target: 8, value: 2}, 
{source: 67, target: 8, value: 2}, 
{source: 68, target: 8, value: 2}, 
{source: 69, target: 8, value: 2}, 
{source: 70, target: 8, value: 2}, 
{source: 43, target: 8, value: 2}, 
{source: 71, target: 8, value: 2}, 
{source: 72, target: 8, value: 2}, 
{source: 73, target: 8, value: 2}, 
{source: 74, target: 8, value: 2}, 
{source: 75, target: 8, value: 2}, 
{source: 76, target: 8, value: 2}, 
{source: 77, target: 8, value: 2}, 
{source: 78, target: 8, value: 2}, 
{source: 79, target: 8, value: 2}, 
{source: 80, target: 8, value: 2}, 
{source: 23, target: 8, value: 2}, 
{source: 81, target: 8, value: 2}, 
{source: 83, target: 82, value: 2}, 
{source: 84, target: 82, value: 2}, 
{source: 85, target: 82, value: 2}, 
{source: 86, target: 82, value: 2}, 
{source: 87, target: 82, value: 2}, 
{source: 88, target: 82, value: 2}, 
{source: 89, target: 82, value: 2}, 
{source: 90, target: 82, value: 2}, 
{source: 91, target: 82, value: 2}, 
{source: 92, target: 82, value: 2}, 
{source: 93, target: 82, value: 2}, 
{source: 94, target: 82, value: 2}, 
{source: 8, target: 82, value: 2}, 
{source: 0, target: 82, value: 2}, 
{source: 95, target: 82, value: 2}, 
{source: 96, target: 82, value: 2}, 
{source: 97, target: 82, value: 2}, 
{source: 98, target: 82, value: 2}, 
{source: 99, target: 82, value: 2}, 
{source: 100, target: 82, value: 2}, 
{source: 46, target: 82, value: 2}, 
{source: 101, target: 82, value: 2}, 
{source: 102, target: 82, value: 2}, 
{source: 20, target: 82, value: 2}, 
{source: 103, target: 82, value: 2}, 
{source: 79, target: 82, value: 2}, 
{source: 50, target: 82, value: 2}, 
{source: 23, target: 82, value: 2}, 
{source: 81, target: 82, value: 2}, 
{source: 104, target: 82, value: 2}
] };
